// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2012-2014 The Regents of the University of California
// SPDX-FileCopyrightText: 2016-2017 SiFive, Inc
// SPDX-FileCopyrightText: 2024 Jiuyang Liu <liu@jiuyang.me>
package org.chipsalliance.rocketv

// The compatibility layer to bridge rvdecoderdb and codegen instructions.
// In the future, this file is going to be removed.
object rvdecoderdbcompat {
  val rvdecoderdbPath = org.chipsalliance.rvdecoderdb.extractResource(getClass.getClassLoader)

  val causes = org.chipsalliance.rvdecoderdb.causes(rvdecoderdbPath)
  object Causes {
    val misaligned_fetch         = causes("misaligned fetch")
    val fetch_access             = causes("fetch access")
    val illegal_instruction      = causes("illegal instruction")
    val breakpoint               = causes("breakpoint")
    val misaligned_load          = causes("misaligned load")
    val load_access              = causes("load access")
    val misaligned_store         = causes("misaligned store")
    val store_access             = causes("store access")
    val user_ecall               = causes("user ecall")
    val supervisor_ecall         = causes("supervisor ecall")
    val virtual_supervisor_ecall = causes("virtual supervisor ecall")
    val machine_ecall            = causes("machine ecall")
    val fetch_page_fault         = causes("fetch page fault")
    val load_page_fault          = causes("load page fault")
    val store_page_fault         = causes("store page fault")
    val fetch_guest_page_fault   = causes("fetch guest page fault")
    val load_guest_page_fault    = causes("load guest page fault")
    val virtual_instruction      = causes("virtual instruction")
    val store_guest_page_fault   = causes("store guest page fault")
    val all                      = {
      val res = collection.mutable.ArrayBuffer[Int]()
      res += misaligned_fetch
      res += fetch_access
      res += illegal_instruction
      res += breakpoint
      res += misaligned_load
      res += load_access
      res += misaligned_store
      res += store_access
      res += user_ecall
      res += supervisor_ecall
      res += virtual_supervisor_ecall
      res += machine_ecall
      res += fetch_page_fault
      res += load_page_fault
      res += store_page_fault
      res += fetch_guest_page_fault
      res += load_guest_page_fault
      res += virtual_instruction
      res += store_guest_page_fault
      res.toArray
    }
  }

  val csrs   = org.chipsalliance.rvdecoderdb.csrs(rvdecoderdbPath).toMap
  val csrs32 = org.chipsalliance.rvdecoderdb.csrs(rvdecoderdbPath).toMap
  object CSRs {
    val fflags        = csrs("fflags")
    val frm           = csrs("frm")
    val fcsr          = csrs("fcsr")
    val vstart        = csrs("vstart")
    val vxsat         = csrs("vxsat")
    val vxrm          = csrs("vxrm")
    val vcsr          = csrs("vcsr")
    val seed          = csrs("seed")
    val jvt           = csrs("jvt")
    val cycle         = csrs("cycle")
    val time          = csrs("time")
    val instret       = csrs("instret")
    val hpmcounter3   = csrs("hpmcounter3")
    val hpmcounter4   = csrs("hpmcounter4")
    val hpmcounter5   = csrs("hpmcounter5")
    val hpmcounter6   = csrs("hpmcounter6")
    val hpmcounter7   = csrs("hpmcounter7")
    val hpmcounter8   = csrs("hpmcounter8")
    val hpmcounter9   = csrs("hpmcounter9")
    val hpmcounter10  = csrs("hpmcounter10")
    val hpmcounter11  = csrs("hpmcounter11")
    val hpmcounter12  = csrs("hpmcounter12")
    val hpmcounter13  = csrs("hpmcounter13")
    val hpmcounter14  = csrs("hpmcounter14")
    val hpmcounter15  = csrs("hpmcounter15")
    val hpmcounter16  = csrs("hpmcounter16")
    val hpmcounter17  = csrs("hpmcounter17")
    val hpmcounter18  = csrs("hpmcounter18")
    val hpmcounter19  = csrs("hpmcounter19")
    val hpmcounter20  = csrs("hpmcounter20")
    val hpmcounter21  = csrs("hpmcounter21")
    val hpmcounter22  = csrs("hpmcounter22")
    val hpmcounter23  = csrs("hpmcounter23")
    val hpmcounter24  = csrs("hpmcounter24")
    val hpmcounter25  = csrs("hpmcounter25")
    val hpmcounter26  = csrs("hpmcounter26")
    val hpmcounter27  = csrs("hpmcounter27")
    val hpmcounter28  = csrs("hpmcounter28")
    val hpmcounter29  = csrs("hpmcounter29")
    val hpmcounter30  = csrs("hpmcounter30")
    val hpmcounter31  = csrs("hpmcounter31")
    val vl            = csrs("vl")
    val vtype         = csrs("vtype")
    val vlenb         = csrs("vlenb")
    val sstatus       = csrs("sstatus")
    val sedeleg       = csrs("sedeleg")
    val sideleg       = csrs("sideleg")
    val sie           = csrs("sie")
    val stvec         = csrs("stvec")
    val scounteren    = csrs("scounteren")
    val senvcfg       = csrs("senvcfg")
    val sstateen0     = csrs("sstateen0")
    val sstateen1     = csrs("sstateen1")
    val sstateen2     = csrs("sstateen2")
    val sstateen3     = csrs("sstateen3")
    val sscratch      = csrs("sscratch")
    val sepc          = csrs("sepc")
    val scause        = csrs("scause")
    val stval         = csrs("stval")
    val sip           = csrs("sip")
    val stimecmp      = csrs("stimecmp")
    val siselect      = csrs("siselect")
    val sireg         = csrs("sireg")
    val stopei        = csrs("stopei")
    val satp          = csrs("satp")
    val scontext      = csrs("scontext")
    val vsstatus      = csrs("vsstatus")
    val vsie          = csrs("vsie")
    val vstvec        = csrs("vstvec")
    val vsscratch     = csrs("vsscratch")
    val vsepc         = csrs("vsepc")
    val vscause       = csrs("vscause")
    val vstval        = csrs("vstval")
    val vsip          = csrs("vsip")
    val vstimecmp     = csrs("vstimecmp")
    val vsiselect     = csrs("vsiselect")
    val vsireg        = csrs("vsireg")
    val vstopei       = csrs("vstopei")
    val vsatp         = csrs("vsatp")
    val hstatus       = csrs("hstatus")
    val hedeleg       = csrs("hedeleg")
    val hideleg       = csrs("hideleg")
    val hie           = csrs("hie")
    val htimedelta    = csrs("htimedelta")
    val hcounteren    = csrs("hcounteren")
    val hgeie         = csrs("hgeie")
    val hvien         = csrs("hvien")
    val hvictl        = csrs("hvictl")
    val henvcfg       = csrs("henvcfg")
    val hstateen0     = csrs("hstateen0")
    val hstateen1     = csrs("hstateen1")
    val hstateen2     = csrs("hstateen2")
    val hstateen3     = csrs("hstateen3")
    val htval         = csrs("htval")
    val hip           = csrs("hip")
    val hvip          = csrs("hvip")
    val hviprio1      = csrs("hviprio1")
    val hviprio2      = csrs("hviprio2")
    val htinst        = csrs("htinst")
    val hgatp         = csrs("hgatp")
    val hcontext      = csrs("hcontext")
    val hgeip         = csrs("hgeip")
    val vstopi        = csrs("vstopi")
    val scountovf     = csrs("scountovf")
    val stopi         = csrs("stopi")
    val utvt          = csrs("utvt")
    val unxti         = csrs("unxti")
    val uintstatus    = csrs("uintstatus")
    val uscratchcsw   = csrs("uscratchcsw")
    val uscratchcswl  = csrs("uscratchcswl")
    val stvt          = csrs("stvt")
    val snxti         = csrs("snxti")
    val sintstatus    = csrs("sintstatus")
    val sscratchcsw   = csrs("sscratchcsw")
    val sscratchcswl  = csrs("sscratchcswl")
    val mtvt          = csrs("mtvt")
    val mnxti         = csrs("mnxti")
    val mintstatus    = csrs("mintstatus")
    val mscratchcsw   = csrs("mscratchcsw")
    val mscratchcswl  = csrs("mscratchcswl")
    val mstatus       = csrs("mstatus")
    val misa          = csrs("misa")
    val medeleg       = csrs("medeleg")
    val mideleg       = csrs("mideleg")
    val mie           = csrs("mie")
    val mtvec         = csrs("mtvec")
    val mcounteren    = csrs("mcounteren")
    val mvien         = csrs("mvien")
    val mvip          = csrs("mvip")
    val menvcfg       = csrs("menvcfg")
    val mstateen0     = csrs("mstateen0")
    val mstateen1     = csrs("mstateen1")
    val mstateen2     = csrs("mstateen2")
    val mstateen3     = csrs("mstateen3")
    val mcountinhibit = csrs("mcountinhibit")
    val mscratch      = csrs("mscratch")
    val mepc          = csrs("mepc")
    val mcause        = csrs("mcause")
    val mtval         = csrs("mtval")
    val mip           = csrs("mip")
    val mtinst        = csrs("mtinst")
    val mtval2        = csrs("mtval2")
    val miselect      = csrs("miselect")
    val mireg         = csrs("mireg")
    val mtopei        = csrs("mtopei")
    val pmpcfg0       = csrs("pmpcfg0")
    val pmpcfg1       = csrs("pmpcfg1")
    val pmpcfg2       = csrs("pmpcfg2")
    val pmpcfg3       = csrs("pmpcfg3")
    val pmpcfg4       = csrs("pmpcfg4")
    val pmpcfg5       = csrs("pmpcfg5")
    val pmpcfg6       = csrs("pmpcfg6")
    val pmpcfg7       = csrs("pmpcfg7")
    val pmpcfg8       = csrs("pmpcfg8")
    val pmpcfg9       = csrs("pmpcfg9")
    val pmpcfg10      = csrs("pmpcfg10")
    val pmpcfg11      = csrs("pmpcfg11")
    val pmpcfg12      = csrs("pmpcfg12")
    val pmpcfg13      = csrs("pmpcfg13")
    val pmpcfg14      = csrs("pmpcfg14")
    val pmpcfg15      = csrs("pmpcfg15")
    val pmpaddr0      = csrs("pmpaddr0")
    val pmpaddr1      = csrs("pmpaddr1")
    val pmpaddr2      = csrs("pmpaddr2")
    val pmpaddr3      = csrs("pmpaddr3")
    val pmpaddr4      = csrs("pmpaddr4")
    val pmpaddr5      = csrs("pmpaddr5")
    val pmpaddr6      = csrs("pmpaddr6")
    val pmpaddr7      = csrs("pmpaddr7")
    val pmpaddr8      = csrs("pmpaddr8")
    val pmpaddr9      = csrs("pmpaddr9")
    val pmpaddr10     = csrs("pmpaddr10")
    val pmpaddr11     = csrs("pmpaddr11")
    val pmpaddr12     = csrs("pmpaddr12")
    val pmpaddr13     = csrs("pmpaddr13")
    val pmpaddr14     = csrs("pmpaddr14")
    val pmpaddr15     = csrs("pmpaddr15")
    val pmpaddr16     = csrs("pmpaddr16")
    val pmpaddr17     = csrs("pmpaddr17")
    val pmpaddr18     = csrs("pmpaddr18")
    val pmpaddr19     = csrs("pmpaddr19")
    val pmpaddr20     = csrs("pmpaddr20")
    val pmpaddr21     = csrs("pmpaddr21")
    val pmpaddr22     = csrs("pmpaddr22")
    val pmpaddr23     = csrs("pmpaddr23")
    val pmpaddr24     = csrs("pmpaddr24")
    val pmpaddr25     = csrs("pmpaddr25")
    val pmpaddr26     = csrs("pmpaddr26")
    val pmpaddr27     = csrs("pmpaddr27")
    val pmpaddr28     = csrs("pmpaddr28")
    val pmpaddr29     = csrs("pmpaddr29")
    val pmpaddr30     = csrs("pmpaddr30")
    val pmpaddr31     = csrs("pmpaddr31")
    val pmpaddr32     = csrs("pmpaddr32")
    val pmpaddr33     = csrs("pmpaddr33")
    val pmpaddr34     = csrs("pmpaddr34")
    val pmpaddr35     = csrs("pmpaddr35")
    val pmpaddr36     = csrs("pmpaddr36")
    val pmpaddr37     = csrs("pmpaddr37")
    val pmpaddr38     = csrs("pmpaddr38")
    val pmpaddr39     = csrs("pmpaddr39")
    val pmpaddr40     = csrs("pmpaddr40")
    val pmpaddr41     = csrs("pmpaddr41")
    val pmpaddr42     = csrs("pmpaddr42")
    val pmpaddr43     = csrs("pmpaddr43")
    val pmpaddr44     = csrs("pmpaddr44")
    val pmpaddr45     = csrs("pmpaddr45")
    val pmpaddr46     = csrs("pmpaddr46")
    val pmpaddr47     = csrs("pmpaddr47")
    val pmpaddr48     = csrs("pmpaddr48")
    val pmpaddr49     = csrs("pmpaddr49")
    val pmpaddr50     = csrs("pmpaddr50")
    val pmpaddr51     = csrs("pmpaddr51")
    val pmpaddr52     = csrs("pmpaddr52")
    val pmpaddr53     = csrs("pmpaddr53")
    val pmpaddr54     = csrs("pmpaddr54")
    val pmpaddr55     = csrs("pmpaddr55")
    val pmpaddr56     = csrs("pmpaddr56")
    val pmpaddr57     = csrs("pmpaddr57")
    val pmpaddr58     = csrs("pmpaddr58")
    val pmpaddr59     = csrs("pmpaddr59")
    val pmpaddr60     = csrs("pmpaddr60")
    val pmpaddr61     = csrs("pmpaddr61")
    val pmpaddr62     = csrs("pmpaddr62")
    val pmpaddr63     = csrs("pmpaddr63")
    val mseccfg       = csrs("mseccfg")
    val tselect       = csrs("tselect")
    val tdata1        = csrs("tdata1")
    val tdata2        = csrs("tdata2")
    val tdata3        = csrs("tdata3")
    val tinfo         = csrs("tinfo")
    val tcontrol      = csrs("tcontrol")
    val mcontext      = csrs("mcontext")
    val mscontext     = csrs("mscontext")
    val dcsr          = csrs("dcsr")
    val dpc           = csrs("dpc")
    val dscratch0     = csrs("dscratch0")
    val dscratch1     = csrs("dscratch1")
    val mcycle        = csrs("mcycle")
    val minstret      = csrs("minstret")
    val mhpmcounter3  = csrs("mhpmcounter3")
    val mhpmcounter4  = csrs("mhpmcounter4")
    val mhpmcounter5  = csrs("mhpmcounter5")
    val mhpmcounter6  = csrs("mhpmcounter6")
    val mhpmcounter7  = csrs("mhpmcounter7")
    val mhpmcounter8  = csrs("mhpmcounter8")
    val mhpmcounter9  = csrs("mhpmcounter9")
    val mhpmcounter10 = csrs("mhpmcounter10")
    val mhpmcounter11 = csrs("mhpmcounter11")
    val mhpmcounter12 = csrs("mhpmcounter12")
    val mhpmcounter13 = csrs("mhpmcounter13")
    val mhpmcounter14 = csrs("mhpmcounter14")
    val mhpmcounter15 = csrs("mhpmcounter15")
    val mhpmcounter16 = csrs("mhpmcounter16")
    val mhpmcounter17 = csrs("mhpmcounter17")
    val mhpmcounter18 = csrs("mhpmcounter18")
    val mhpmcounter19 = csrs("mhpmcounter19")
    val mhpmcounter20 = csrs("mhpmcounter20")
    val mhpmcounter21 = csrs("mhpmcounter21")
    val mhpmcounter22 = csrs("mhpmcounter22")
    val mhpmcounter23 = csrs("mhpmcounter23")
    val mhpmcounter24 = csrs("mhpmcounter24")
    val mhpmcounter25 = csrs("mhpmcounter25")
    val mhpmcounter26 = csrs("mhpmcounter26")
    val mhpmcounter27 = csrs("mhpmcounter27")
    val mhpmcounter28 = csrs("mhpmcounter28")
    val mhpmcounter29 = csrs("mhpmcounter29")
    val mhpmcounter30 = csrs("mhpmcounter30")
    val mhpmcounter31 = csrs("mhpmcounter31")
    val mhpmevent3    = csrs("mhpmevent3")
    val mhpmevent4    = csrs("mhpmevent4")
    val mhpmevent5    = csrs("mhpmevent5")
    val mhpmevent6    = csrs("mhpmevent6")
    val mhpmevent7    = csrs("mhpmevent7")
    val mhpmevent8    = csrs("mhpmevent8")
    val mhpmevent9    = csrs("mhpmevent9")
    val mhpmevent10   = csrs("mhpmevent10")
    val mhpmevent11   = csrs("mhpmevent11")
    val mhpmevent12   = csrs("mhpmevent12")
    val mhpmevent13   = csrs("mhpmevent13")
    val mhpmevent14   = csrs("mhpmevent14")
    val mhpmevent15   = csrs("mhpmevent15")
    val mhpmevent16   = csrs("mhpmevent16")
    val mhpmevent17   = csrs("mhpmevent17")
    val mhpmevent18   = csrs("mhpmevent18")
    val mhpmevent19   = csrs("mhpmevent19")
    val mhpmevent20   = csrs("mhpmevent20")
    val mhpmevent21   = csrs("mhpmevent21")
    val mhpmevent22   = csrs("mhpmevent22")
    val mhpmevent23   = csrs("mhpmevent23")
    val mhpmevent24   = csrs("mhpmevent24")
    val mhpmevent25   = csrs("mhpmevent25")
    val mhpmevent26   = csrs("mhpmevent26")
    val mhpmevent27   = csrs("mhpmevent27")
    val mhpmevent28   = csrs("mhpmevent28")
    val mhpmevent29   = csrs("mhpmevent29")
    val mhpmevent30   = csrs("mhpmevent30")
    val mhpmevent31   = csrs("mhpmevent31")
    val mvendorid     = csrs("mvendorid")
    val marchid       = csrs("marchid")
    val mimpid        = csrs("mimpid")
    val mhartid       = csrs("mhartid")
    val mconfigptr    = csrs("mconfigptr")
    val mtopi         = csrs("mtopi")

    val sieh           = csrs32("sieh")
    val siph           = csrs32("siph")
    val stimecmph      = csrs32("stimecmph")
    val vsieh          = csrs32("vsieh")
    val vsiph          = csrs32("vsiph")
    val vstimecmph     = csrs32("vstimecmph")
    val htimedeltah    = csrs32("htimedeltah")
    val hidelegh       = csrs32("hidelegh")
    val hvienh         = csrs32("hvienh")
    val henvcfgh       = csrs32("henvcfgh")
    val hviph          = csrs32("hviph")
    val hviprio1h      = csrs32("hviprio1h")
    val hviprio2h      = csrs32("hviprio2h")
    val hstateen0h     = csrs32("hstateen0h")
    val hstateen1h     = csrs32("hstateen1h")
    val hstateen2h     = csrs32("hstateen2h")
    val hstateen3h     = csrs32("hstateen3h")
    val cycleh         = csrs32("cycleh")
    val timeh          = csrs32("timeh")
    val instreth       = csrs32("instreth")
    val hpmcounter3h   = csrs32("hpmcounter3h")
    val hpmcounter4h   = csrs32("hpmcounter4h")
    val hpmcounter5h   = csrs32("hpmcounter5h")
    val hpmcounter6h   = csrs32("hpmcounter6h")
    val hpmcounter7h   = csrs32("hpmcounter7h")
    val hpmcounter8h   = csrs32("hpmcounter8h")
    val hpmcounter9h   = csrs32("hpmcounter9h")
    val hpmcounter10h  = csrs32("hpmcounter10h")
    val hpmcounter11h  = csrs32("hpmcounter11h")
    val hpmcounter12h  = csrs32("hpmcounter12h")
    val hpmcounter13h  = csrs32("hpmcounter13h")
    val hpmcounter14h  = csrs32("hpmcounter14h")
    val hpmcounter15h  = csrs32("hpmcounter15h")
    val hpmcounter16h  = csrs32("hpmcounter16h")
    val hpmcounter17h  = csrs32("hpmcounter17h")
    val hpmcounter18h  = csrs32("hpmcounter18h")
    val hpmcounter19h  = csrs32("hpmcounter19h")
    val hpmcounter20h  = csrs32("hpmcounter20h")
    val hpmcounter21h  = csrs32("hpmcounter21h")
    val hpmcounter22h  = csrs32("hpmcounter22h")
    val hpmcounter23h  = csrs32("hpmcounter23h")
    val hpmcounter24h  = csrs32("hpmcounter24h")
    val hpmcounter25h  = csrs32("hpmcounter25h")
    val hpmcounter26h  = csrs32("hpmcounter26h")
    val hpmcounter27h  = csrs32("hpmcounter27h")
    val hpmcounter28h  = csrs32("hpmcounter28h")
    val hpmcounter29h  = csrs32("hpmcounter29h")
    val hpmcounter30h  = csrs32("hpmcounter30h")
    val hpmcounter31h  = csrs32("hpmcounter31h")
    val mstatush       = csrs32("mstatush")
    val midelegh       = csrs32("midelegh")
    val mieh           = csrs32("mieh")
    val mvienh         = csrs32("mvienh")
    val mviph          = csrs32("mviph")
    val menvcfgh       = csrs32("menvcfgh")
    val mstateen0h     = csrs32("mstateen0h")
    val mstateen1h     = csrs32("mstateen1h")
    val mstateen2h     = csrs32("mstateen2h")
    val mstateen3h     = csrs32("mstateen3h")
    val miph           = csrs32("miph")
    val mhpmevent3h    = csrs32("mhpmevent3h")
    val mhpmevent4h    = csrs32("mhpmevent4h")
    val mhpmevent5h    = csrs32("mhpmevent5h")
    val mhpmevent6h    = csrs32("mhpmevent6h")
    val mhpmevent7h    = csrs32("mhpmevent7h")
    val mhpmevent8h    = csrs32("mhpmevent8h")
    val mhpmevent9h    = csrs32("mhpmevent9h")
    val mhpmevent10h   = csrs32("mhpmevent10h")
    val mhpmevent11h   = csrs32("mhpmevent11h")
    val mhpmevent12h   = csrs32("mhpmevent12h")
    val mhpmevent13h   = csrs32("mhpmevent13h")
    val mhpmevent14h   = csrs32("mhpmevent14h")
    val mhpmevent15h   = csrs32("mhpmevent15h")
    val mhpmevent16h   = csrs32("mhpmevent16h")
    val mhpmevent17h   = csrs32("mhpmevent17h")
    val mhpmevent18h   = csrs32("mhpmevent18h")
    val mhpmevent19h   = csrs32("mhpmevent19h")
    val mhpmevent20h   = csrs32("mhpmevent20h")
    val mhpmevent21h   = csrs32("mhpmevent21h")
    val mhpmevent22h   = csrs32("mhpmevent22h")
    val mhpmevent23h   = csrs32("mhpmevent23h")
    val mhpmevent24h   = csrs32("mhpmevent24h")
    val mhpmevent25h   = csrs32("mhpmevent25h")
    val mhpmevent26h   = csrs32("mhpmevent26h")
    val mhpmevent27h   = csrs32("mhpmevent27h")
    val mhpmevent28h   = csrs32("mhpmevent28h")
    val mhpmevent29h   = csrs32("mhpmevent29h")
    val mhpmevent30h   = csrs32("mhpmevent30h")
    val mhpmevent31h   = csrs32("mhpmevent31h")
    val mnscratch      = csrs32("mnscratch")
    val mnepc          = csrs32("mnepc")
    val mncause        = csrs32("mncause")
    val mnstatus       = csrs32("mnstatus")
    val mseccfgh       = csrs32("mseccfgh")
    val mcycleh        = csrs32("mcycleh")
    val minstreth      = csrs32("minstreth")
    val mhpmcounter3h  = csrs32("mhpmcounter3h")
    val mhpmcounter4h  = csrs32("mhpmcounter4h")
    val mhpmcounter5h  = csrs32("mhpmcounter5h")
    val mhpmcounter6h  = csrs32("mhpmcounter6h")
    val mhpmcounter7h  = csrs32("mhpmcounter7h")
    val mhpmcounter8h  = csrs32("mhpmcounter8h")
    val mhpmcounter9h  = csrs32("mhpmcounter9h")
    val mhpmcounter10h = csrs32("mhpmcounter10h")
    val mhpmcounter11h = csrs32("mhpmcounter11h")
    val mhpmcounter12h = csrs32("mhpmcounter12h")
    val mhpmcounter13h = csrs32("mhpmcounter13h")
    val mhpmcounter14h = csrs32("mhpmcounter14h")
    val mhpmcounter15h = csrs32("mhpmcounter15h")
    val mhpmcounter16h = csrs32("mhpmcounter16h")
    val mhpmcounter17h = csrs32("mhpmcounter17h")
    val mhpmcounter18h = csrs32("mhpmcounter18h")
    val mhpmcounter19h = csrs32("mhpmcounter19h")
    val mhpmcounter20h = csrs32("mhpmcounter20h")
    val mhpmcounter21h = csrs32("mhpmcounter21h")
    val mhpmcounter22h = csrs32("mhpmcounter22h")
    val mhpmcounter23h = csrs32("mhpmcounter23h")
    val mhpmcounter24h = csrs32("mhpmcounter24h")
    val mhpmcounter25h = csrs32("mhpmcounter25h")
    val mhpmcounter26h = csrs32("mhpmcounter26h")
    val mhpmcounter27h = csrs32("mhpmcounter27h")
    val mhpmcounter28h = csrs32("mhpmcounter28h")
    val mhpmcounter29h = csrs32("mhpmcounter29h")
    val mhpmcounter30h = csrs32("mhpmcounter30h")
    val mhpmcounter31h = csrs32("mhpmcounter31h")

    val all   = {
      val res = collection.mutable.ArrayBuffer[Int]()
      res += fflags
      res += frm
      res += fcsr
      res += vstart
      res += vxsat
      res += vxrm
      res += vcsr
      res += seed
      res += jvt
      res += cycle
      res += time
      res += instret
      res += hpmcounter3
      res += hpmcounter4
      res += hpmcounter5
      res += hpmcounter6
      res += hpmcounter7
      res += hpmcounter8
      res += hpmcounter9
      res += hpmcounter10
      res += hpmcounter11
      res += hpmcounter12
      res += hpmcounter13
      res += hpmcounter14
      res += hpmcounter15
      res += hpmcounter16
      res += hpmcounter17
      res += hpmcounter18
      res += hpmcounter19
      res += hpmcounter20
      res += hpmcounter21
      res += hpmcounter22
      res += hpmcounter23
      res += hpmcounter24
      res += hpmcounter25
      res += hpmcounter26
      res += hpmcounter27
      res += hpmcounter28
      res += hpmcounter29
      res += hpmcounter30
      res += hpmcounter31
      res += vl
      res += vtype
      res += vlenb
      res += sstatus
      res += sedeleg
      res += sideleg
      res += sie
      res += stvec
      res += scounteren
      res += senvcfg
      res += sstateen0
      res += sstateen1
      res += sstateen2
      res += sstateen3
      res += sscratch
      res += sepc
      res += scause
      res += stval
      res += sip
      res += stimecmp
      res += siselect
      res += sireg
      res += stopei
      res += satp
      res += scontext
      res += vsstatus
      res += vsie
      res += vstvec
      res += vsscratch
      res += vsepc
      res += vscause
      res += vstval
      res += vsip
      res += vstimecmp
      res += vsiselect
      res += vsireg
      res += vstopei
      res += vsatp
      res += hstatus
      res += hedeleg
      res += hideleg
      res += hie
      res += htimedelta
      res += hcounteren
      res += hgeie
      res += hvien
      res += hvictl
      res += henvcfg
      res += hstateen0
      res += hstateen1
      res += hstateen2
      res += hstateen3
      res += htval
      res += hip
      res += hvip
      res += hviprio1
      res += hviprio2
      res += htinst
      res += hgatp
      res += hcontext
      res += hgeip
      res += vstopi
      res += scountovf
      res += stopi
      res += utvt
      res += unxti
      res += uintstatus
      res += uscratchcsw
      res += uscratchcswl
      res += stvt
      res += snxti
      res += sintstatus
      res += sscratchcsw
      res += sscratchcswl
      res += mtvt
      res += mnxti
      res += mintstatus
      res += mscratchcsw
      res += mscratchcswl
      res += mstatus
      res += misa
      res += medeleg
      res += mideleg
      res += mie
      res += mtvec
      res += mcounteren
      res += mvien
      res += mvip
      res += menvcfg
      res += mstateen0
      res += mstateen1
      res += mstateen2
      res += mstateen3
      res += mcountinhibit
      res += mscratch
      res += mepc
      res += mcause
      res += mtval
      res += mip
      res += mtinst
      res += mtval2
      res += miselect
      res += mireg
      res += mtopei
      res += pmpcfg0
      res += pmpcfg1
      res += pmpcfg2
      res += pmpcfg3
      res += pmpcfg4
      res += pmpcfg5
      res += pmpcfg6
      res += pmpcfg7
      res += pmpcfg8
      res += pmpcfg9
      res += pmpcfg10
      res += pmpcfg11
      res += pmpcfg12
      res += pmpcfg13
      res += pmpcfg14
      res += pmpcfg15
      res += pmpaddr0
      res += pmpaddr1
      res += pmpaddr2
      res += pmpaddr3
      res += pmpaddr4
      res += pmpaddr5
      res += pmpaddr6
      res += pmpaddr7
      res += pmpaddr8
      res += pmpaddr9
      res += pmpaddr10
      res += pmpaddr11
      res += pmpaddr12
      res += pmpaddr13
      res += pmpaddr14
      res += pmpaddr15
      res += pmpaddr16
      res += pmpaddr17
      res += pmpaddr18
      res += pmpaddr19
      res += pmpaddr20
      res += pmpaddr21
      res += pmpaddr22
      res += pmpaddr23
      res += pmpaddr24
      res += pmpaddr25
      res += pmpaddr26
      res += pmpaddr27
      res += pmpaddr28
      res += pmpaddr29
      res += pmpaddr30
      res += pmpaddr31
      res += pmpaddr32
      res += pmpaddr33
      res += pmpaddr34
      res += pmpaddr35
      res += pmpaddr36
      res += pmpaddr37
      res += pmpaddr38
      res += pmpaddr39
      res += pmpaddr40
      res += pmpaddr41
      res += pmpaddr42
      res += pmpaddr43
      res += pmpaddr44
      res += pmpaddr45
      res += pmpaddr46
      res += pmpaddr47
      res += pmpaddr48
      res += pmpaddr49
      res += pmpaddr50
      res += pmpaddr51
      res += pmpaddr52
      res += pmpaddr53
      res += pmpaddr54
      res += pmpaddr55
      res += pmpaddr56
      res += pmpaddr57
      res += pmpaddr58
      res += pmpaddr59
      res += pmpaddr60
      res += pmpaddr61
      res += pmpaddr62
      res += pmpaddr63
      res += mseccfg
      res += tselect
      res += tdata1
      res += tdata2
      res += tdata3
      res += tinfo
      res += tcontrol
      res += mcontext
      res += mscontext
      res += dcsr
      res += dpc
      res += dscratch0
      res += dscratch1
      res += mcycle
      res += minstret
      res += mhpmcounter3
      res += mhpmcounter4
      res += mhpmcounter5
      res += mhpmcounter6
      res += mhpmcounter7
      res += mhpmcounter8
      res += mhpmcounter9
      res += mhpmcounter10
      res += mhpmcounter11
      res += mhpmcounter12
      res += mhpmcounter13
      res += mhpmcounter14
      res += mhpmcounter15
      res += mhpmcounter16
      res += mhpmcounter17
      res += mhpmcounter18
      res += mhpmcounter19
      res += mhpmcounter20
      res += mhpmcounter21
      res += mhpmcounter22
      res += mhpmcounter23
      res += mhpmcounter24
      res += mhpmcounter25
      res += mhpmcounter26
      res += mhpmcounter27
      res += mhpmcounter28
      res += mhpmcounter29
      res += mhpmcounter30
      res += mhpmcounter31
      res += mhpmevent3
      res += mhpmevent4
      res += mhpmevent5
      res += mhpmevent6
      res += mhpmevent7
      res += mhpmevent8
      res += mhpmevent9
      res += mhpmevent10
      res += mhpmevent11
      res += mhpmevent12
      res += mhpmevent13
      res += mhpmevent14
      res += mhpmevent15
      res += mhpmevent16
      res += mhpmevent17
      res += mhpmevent18
      res += mhpmevent19
      res += mhpmevent20
      res += mhpmevent21
      res += mhpmevent22
      res += mhpmevent23
      res += mhpmevent24
      res += mhpmevent25
      res += mhpmevent26
      res += mhpmevent27
      res += mhpmevent28
      res += mhpmevent29
      res += mhpmevent30
      res += mhpmevent31
      res += mvendorid
      res += marchid
      res += mimpid
      res += mhartid
      res += mconfigptr
      res += mtopi
      res.toArray
    }
    val all32 = {
      val res = collection.mutable.ArrayBuffer(all: _*)
      res += sieh
      res += siph
      res += stimecmph
      res += vsieh
      res += vsiph
      res += vstimecmph
      res += htimedeltah
      res += hidelegh
      res += hvienh
      res += henvcfgh
      res += hviph
      res += hviprio1h
      res += hviprio2h
      res += hstateen0h
      res += hstateen1h
      res += hstateen2h
      res += hstateen3h
      res += cycleh
      res += timeh
      res += instreth
      res += hpmcounter3h
      res += hpmcounter4h
      res += hpmcounter5h
      res += hpmcounter6h
      res += hpmcounter7h
      res += hpmcounter8h
      res += hpmcounter9h
      res += hpmcounter10h
      res += hpmcounter11h
      res += hpmcounter12h
      res += hpmcounter13h
      res += hpmcounter14h
      res += hpmcounter15h
      res += hpmcounter16h
      res += hpmcounter17h
      res += hpmcounter18h
      res += hpmcounter19h
      res += hpmcounter20h
      res += hpmcounter21h
      res += hpmcounter22h
      res += hpmcounter23h
      res += hpmcounter24h
      res += hpmcounter25h
      res += hpmcounter26h
      res += hpmcounter27h
      res += hpmcounter28h
      res += hpmcounter29h
      res += hpmcounter30h
      res += hpmcounter31h
      res += mstatush
      res += midelegh
      res += mieh
      res += mvienh
      res += mviph
      res += menvcfgh
      res += mstateen0h
      res += mstateen1h
      res += mstateen2h
      res += mstateen3h
      res += miph
      res += mhpmevent3h
      res += mhpmevent4h
      res += mhpmevent5h
      res += mhpmevent6h
      res += mhpmevent7h
      res += mhpmevent8h
      res += mhpmevent9h
      res += mhpmevent10h
      res += mhpmevent11h
      res += mhpmevent12h
      res += mhpmevent13h
      res += mhpmevent14h
      res += mhpmevent15h
      res += mhpmevent16h
      res += mhpmevent17h
      res += mhpmevent18h
      res += mhpmevent19h
      res += mhpmevent20h
      res += mhpmevent21h
      res += mhpmevent22h
      res += mhpmevent23h
      res += mhpmevent24h
      res += mhpmevent25h
      res += mhpmevent26h
      res += mhpmevent27h
      res += mhpmevent28h
      res += mhpmevent29h
      res += mhpmevent30h
      res += mhpmevent31h
      res += mnscratch
      res += mnepc
      res += mncause
      res += mnstatus
      res += mseccfgh
      res += mcycleh
      res += minstreth
      res += mhpmcounter3h
      res += mhpmcounter4h
      res += mhpmcounter5h
      res += mhpmcounter6h
      res += mhpmcounter7h
      res += mhpmcounter8h
      res += mhpmcounter9h
      res += mhpmcounter10h
      res += mhpmcounter11h
      res += mhpmcounter12h
      res += mhpmcounter13h
      res += mhpmcounter14h
      res += mhpmcounter15h
      res += mhpmcounter16h
      res += mhpmcounter17h
      res += mhpmcounter18h
      res += mhpmcounter19h
      res += mhpmcounter20h
      res += mhpmcounter21h
      res += mhpmcounter22h
      res += mhpmcounter23h
      res += mhpmcounter24h
      res += mhpmcounter25h
      res += mhpmcounter26h
      res += mhpmcounter27h
      res += mhpmcounter28h
      res += mhpmcounter29h
      res += mhpmcounter30h
      res += mhpmcounter31h
      res.toArray
    }
  }

  object CustomCSRs {
    val mnscratch = 0x350
    val mnepc     = 0x351
    val mncause   = 0x352
    val mnstatus  = 0x353
    val all       = {
      val res = collection.mutable.ArrayBuffer[Int]()
      res += mnscratch
      res += mnepc
      res += mncause
      res += mnstatus
      res.toArray
    }
    val all32     = {
      val res = collection.mutable.ArrayBuffer(all: _*)
      res.toArray
    }
  }
}
