# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  arithmetic = {
    pname = "arithmetic";
    version = "7f167dd90874afa5717fcfb1b8bbfb15ba6317a7";
    src = fetchFromGitHub {
      owner = "sequencer";
      repo = "arithmetic";
      rev = "7f167dd90874afa5717fcfb1b8bbfb15ba6317a7";
      fetchSubmodules = false;
      sha256 = "sha256-gCduOy1xKPH3sP6pU4IegF0270h+UNoP1cErgBQzuCs=";
    };
    date = "2025-02-07";
  };
  berkeley-hardfloat = {
    pname = "berkeley-hardfloat";
    version = "26f00d00c3f3f57480065e02bfcfde3d3b41ec51";
    src = fetchFromGitHub {
      owner = "ucb-bar";
      repo = "berkeley-hardfloat";
      rev = "26f00d00c3f3f57480065e02bfcfde3d3b41ec51";
      fetchSubmodules = false;
      sha256 = "sha256-gA1Ol7xnzC+10lGwK9+ftfJcMhKsC0KhjENQvUg3u88=";
    };
    date = "2024-06-05";
  };
  chisel = {
    pname = "chisel";
    version = "f4dc077ac710ca0b4580ffaa8ca68bc8a19aa6ad";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel";
      rev = "f4dc077ac710ca0b4580ffaa8ca68bc8a19aa6ad";
      fetchSubmodules = false;
      sha256 = "sha256-B2NFV0rDC0sSIdG9KH2pgV+72dPN22Sf3JyrzXCbUFc=";
    };
    date = "2025-02-07";
  };
  chisel-interface = {
    pname = "chisel-interface";
    version = "e228636d406a948e5e56d841e877591485bfcb22";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel-interface";
      rev = "e228636d406a948e5e56d841e877591485bfcb22";
      fetchSubmodules = false;
      sha256 = "sha256-CTi9AaVEIagN8HahvihAEtFzc76deKRzBZqX/4V9u8Y=";
    };
    date = "2025-01-30";
  };
  riscv-opcodes = {
    pname = "riscv-opcodes";
    version = "21dab92c834bf782e67034deab87b6bd1952c8ef";
    src = fetchFromGitHub {
      owner = "riscv";
      repo = "riscv-opcodes";
      rev = "21dab92c834bf782e67034deab87b6bd1952c8ef";
      fetchSubmodules = false;
      sha256 = "sha256-8jkSaSnKKYVLhbautY7IC1SqWXDjd+mvgzkH7Yp6vYg=";
    };
    date = "2025-02-07";
  };
  rvdecoderdb = {
    pname = "rvdecoderdb";
    version = "4572bb92fa458f27228ec0ad1aada2a9b7ea92d1";
    src = fetchFromGitHub {
      owner = "sequencer";
      repo = "rvdecoderdb";
      rev = "4572bb92fa458f27228ec0ad1aada2a9b7ea92d1";
      fetchSubmodules = false;
      sha256 = "sha256-h6lUBQFeLfWY4cjyp/YImISUMcUvg15V/EJxc1RJoIQ=";
    };
    date = "2025-02-06";
  };
}
