# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  arithmetic = {
    pname = "arithmetic";
    version = "1a606166317d7cfd5fda8ec5816a7d5374f002bc";
    src = fetchFromGitHub {
      owner = "sequencer";
      repo = "arithmetic";
      rev = "1a606166317d7cfd5fda8ec5816a7d5374f002bc";
      fetchSubmodules = false;
      sha256 = "sha256-Z0Rm81L79qlleIy/wRb3hkaab/RG9HKANeksZj2mRzQ=";
    };
    date = "2025-01-26";
  };
  berkeley-hardfloat = {
    pname = "berkeley-hardfloat";
    version = "26f00d00c3f3f57480065e02bfcfde3d3b41ec51";
    src = fetchFromGitHub {
      owner = "ucb-bar";
      repo = "berkeley-hardfloat";
      rev = "26f00d00c3f3f57480065e02bfcfde3d3b41ec51";
      fetchSubmodules = false;
      sha256 = "sha256-gA1Ol7xnzC+10lGwK9+ftfJcMhKsC0KhjENQvUg3u88=";
    };
    date = "2024-06-05";
  };
  chisel = {
    pname = "chisel";
    version = "1ac76764f2cfd2d37f5f25e4f9b42da665ffd5f0";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel";
      rev = "1ac76764f2cfd2d37f5f25e4f9b42da665ffd5f0";
      fetchSubmodules = false;
      sha256 = "sha256-1ZM4IOL7mWqA5/EP/WLQJi8teqLyqU4f8E8ZTh0wzVQ=";
    };
    date = "2025-01-29";
  };
  chisel-interface = {
    pname = "chisel-interface";
    version = "e228636d406a948e5e56d841e877591485bfcb22";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel-interface";
      rev = "e228636d406a948e5e56d841e877591485bfcb22";
      fetchSubmodules = false;
      sha256 = "sha256-CTi9AaVEIagN8HahvihAEtFzc76deKRzBZqX/4V9u8Y=";
    };
    date = "2025-01-30";
  };
  riscv-opcodes = {
    pname = "riscv-opcodes";
    version = "9f70bcd37db27fddd34b4aa0524b8f19d31e9bb8";
    src = fetchFromGitHub {
      owner = "riscv";
      repo = "riscv-opcodes";
      rev = "9f70bcd37db27fddd34b4aa0524b8f19d31e9bb8";
      fetchSubmodules = false;
      sha256 = "sha256-1X8D2BVMbKnr2qhrKPh1Uubmuezg9nK3ih3QqRKHlCA=";
    };
    date = "2025-01-29";
  };
  rvdecoderdb = {
    pname = "rvdecoderdb";
    version = "1d8d107314291d1d7864549fc04e2155ba22d845";
    src = fetchFromGitHub {
      owner = "sequencer";
      repo = "rvdecoderdb";
      rev = "1d8d107314291d1d7864549fc04e2155ba22d845";
      fetchSubmodules = false;
      sha256 = "sha256-SonFZpmlH26YZ8kpLJoamxQgPX4u+Ch1eaHe48uXczs=";
    };
    date = "2025-01-26";
  };
}
