// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2022 Jiuyang Liu <liu@jiuyang.me>

package org.chipsalliance.t1.rtl.decoder.attribute

import org.chipsalliance.t1.rtl.decoder.T1DecodePattern

object isMa {
  def apply(t1DecodePattern: T1DecodePattern): isMa =
    Seq(
      y _ -> Y,
      n _ -> N,
      dc _ -> DC
    ).collectFirst {
      case (fn, tri) if fn(t1DecodePattern) => isMa(tri)
    }.get

  def y(t1DecodePattern: T1DecodePattern): Boolean = {
    val allMatched = Seq(
      "vadc.vim",
      "vadc.vvm",
      "vadc.vxm",
      "vcompress.vm",
      "vcpop.m",
      "vfirst.m",
      "vfmacc.vf",
      "vfmacc.vv",
      "vfmadd.vf",
      "vfmadd.vv",
      "vfmax.vf",
      "vfmax.vv",
      "vfmerge.vfm",
      "vfmv.v.f",
      "vfmsac.vf",
      "vfmsac.vv",
      "vfmsub.vf",
      "vfmsub.vv",
      "vfmv.f.s",
      "vfmv.s.f",
      "vfnmacc.vf",
      "vfnmacc.vv",
      "vfnmadd.vf",
      "vfnmadd.vv",
      "vfnmsac.vf",
      "vfnmsac.vv",
      "vfnmsub.vf",
      "vfnmsub.vv",
      "vfredmax.vs",
      "vfredmin.vs",
      "vfredosum.vs",
      "vfredusum.vs",
      "vfslide1down.vf",
      "vfslide1up.vf",
      "vfwmacc.vf",
      "vfwmacc.vv",
      "vfwnmacc.vf",
      "vfwnmacc.vv",
      "vfwredosum.vs",
      "vfwredusum.vs",
      "viota.m",
      "vmacc.vv",
      "vmacc.vx",
      "vmadc.vi",
      "vmadc.vim",
      "vmadc.vv",
      "vmadc.vvm",
      "vmadc.vx",
      "vmadc.vxm",
      "vmadd.vv",
      "vmadd.vx",
      "vmand.mm",
      "vmandn.mm",
      "vmax.vv",
      "vmax.vx",
      "vmaxu.vv",
      "vmaxu.vx",
      "vmerge.vim",
      "vmv.v.i",
      "vmerge.vvm",
      "vmv.v.v",
      "vmerge.vxm",
      "vmv.v.x",
      "vmfeq.vf",
      "vmfeq.vv",
      "vmfge.vf",
      "vmfgt.vf",
      "vmfle.vf",
      "vmfle.vv",
      "vmflt.vf",
      "vmflt.vv",
      "vmfne.vf",
      "vmfne.vv",
      "vmnand.mm",
      "vmnor.mm",
      "vmor.mm",
      "vmorn.mm",
      "vmsbc.vv",
      "vmsbc.vvm",
      "vmsbc.vx",
      "vmsbc.vxm",
      "vmsbf.m",
      "vmseq.vi",
      "vmseq.vv",
      "vmseq.vx",
      "vmsgt.vi",
      "vmsgt.vx",
      "vmsgtu.vi",
      "vmsgtu.vx",
      "vmsif.m",
      "vmsle.vi",
      "vmsle.vv",
      "vmsle.vx",
      "vmsleu.vi",
      "vmsleu.vv",
      "vmsleu.vx",
      "vmslt.vv",
      "vmslt.vx",
      "vmsltu.vv",
      "vmsltu.vx",
      "vmsne.vi",
      "vmsne.vv",
      "vmsne.vx",
      "vmsof.m",
      "vmv.s.x",
      "vmv.x.s",
      "vmxnor.mm",
      "vmxor.mm",
      "vnmsac.vv",
      "vnmsac.vx",
      "vnmsub.vv",
      "vnmsub.vx",
      "vredand.vs",
      "vredmax.vs",
      "vredmaxu.vs",
      "vredmin.vs",
      "vredminu.vs",
      "vredor.vs",
      "vredsum.vs",
      "vredxor.vs",
      "vrgather.vv",
      "vrgatherei16.vv",
      "vsbc.vvm",
      "vsbc.vxm",
      "vsext.vf2",
      "vsext.vf4",
      "vsext.vf8",
      "vslide1down.vx",
      "vslide1up.vx",
      "vslidedown.vi",
      "vslidedown.vx",
      "vslideup.vi",
      "vslideup.vx",
      "vwmacc.vv",
      "vwmacc.vx",
      "vwmaccsu.vv",
      "vwmaccsu.vx",
      "vwmaccu.vv",
      "vwmaccu.vx",
      "vwmaccus.vx",
      "vwredsum.vs",
      "vwredsumu.vs",
      "vzext.vf2",
      "vzext.vf4",
      "vzext.vf8",
    )
    allMatched.contains(t1DecodePattern.instruction.name)
  }
  def n(t1DecodePattern: T1DecodePattern): Boolean = {
    val allMatched = t1DecodePattern.param.allInstructions.filter(i =>
      !(y(t1DecodePattern) || dc(t1DecodePattern))
    )
    allMatched.contains(t1DecodePattern.instruction)
  }

  def dc(t1DecodePattern: T1DecodePattern): Boolean = false
}

case class isMa(value: TriState) extends BooleanDecodeAttribute {
  override val description: String = "decodeResult(Decoder.multiplier) && decodeResult(Decoder.uop)(1, 0).xorR && !decodeResult(Decoder.vwmacc) TODO: remove it. */ "
}
