#!/usr/bin/env bash

(return 0 2>/dev/null) && _IS_EXEC=0 || _IS_EXEC=1

set -e
set -o pipefail

if [[ "$(basename $PWD)" != "dependencies" ]]; then
  echo "Please run this script in 'dependencies' directory" >&2
  exit 1
fi

function main() {
  local workdir=$(mktemp -t -d "t1_bootstrap_XXX")
  echo "Using workdir: $workdir"

  local allSubmodulesNameJson=$(nix eval --json '.#t1.submodules.sources' --apply 'srcs: builtins.attrNames srcs')
  local allSubmodules=($(echo "$allSubmodulesNameJson" | jq -r '.[]'))
  mkdir -p "$workdir/submodules"
  for name in "${allSubmodules[@]}"; do
    mkdir -p "$workdir/submodules/$name"
    p=$(nix build ".#t1.submodules.sources.$name.src" --print-out-paths --no-link)
    cp -rT "$p" "$workdir/submodules/$name"
    unset p
  done

  local extraSources=("./berkeley-hardfloat")
  for src in "${extraSources[@]}"; do
    cp -r "$src" "$workdir/submodules/"
  done

  chown -R $USER:$USER "$workdir/submodules"
  chmod -R u+w "$workdir/submodules"

  mkdir -p "$workdir/millUserHome"
  CHECKOUT_ROOT_DIR="$workdir/submodules" \
    MILL_HOME="$millUserHome" \
    ./gennix
}

if (($_IS_EXEC)); then
  main
fi
