#!/usr/bin/env bash

(return 0 2>/dev/null) && _IS_EXEC=0 || _IS_EXEC=1

set -e

if [[ "$(basename $PWD)" != "dependencies" ]]; then
  echo "Please run this script in 'dependencies' directory" >&2
  exit 1
fi

function pathToModule() {
  local path="$1"; shift
  if [[ -z "$path" ]]; then
    echo "No arguments" >&2
    return 1
  fi

  local safePath="$(echo "$path" | sed 's/.//' | sed 's|/| |g' | xargs)"
  IFS=' ' read -ra segments <<< "$safePath"

  _ifs="$IFS"
  IFS='.'
  echo "${segments[*]}"

  IFS="$_ifs"
  unset segments
}

function patchMillRepo() {
  local oldRoot="$1"; shift
  local newRoot="$1"; shift

  echo "Patching repository"
  mv build.mill package.mill
  # Replace `package build`
  sed -i "s/^package ${oldRoot}$/package ${newRoot}/" package.mill
  if [[ -f "common.mill" ]]; then
    sed -i "s/^package ${oldRoot}$/package ${newRoot}/" common.mill
  fi
}

function main() {
  export PATH="$(nix build '.#jq.bin' --no-warn-dirty --no-link --print-out-paths)/bin:$PATH"
  export PATH="$(nix build '.#git' --no-warn-dirty --no-link --print-out-paths)/bin:$PATH"

  local nvfetcherSourceJson=${NVFETCHER_SOURCE_JSON:-../nix/t1/dependencies/_sources/generated.json}
  if [[ ! -f "$nvfetcherSourceJson" ]]; then
    echo "\$NVFETCHER_SOURCE_JSON file $nvfetcherSourceJson not found" >&2
    exit 1
  fi

  local rootDir=${CHECKOUT_ROOT_DIR:-$(mktemp -d -t "t1-deps-source-XXX")}

  local vendorInfos=( $(jq -r \
    'to_entries[] | "\(.key),https://github.com/\(.value.src.owner)/\(.value.src.repo).git,\(.value.src.rev)"' \
    "$nvfetcherSourceJson") )

  for info in "${vendorInfos[@]}"; do
    echo
    IFS=',' read -r name url rev <<< "$info"

    echo "Handling repo: $name"
    git clone --depth=1 "$url" "$rootDir/$name"
    pushd "$rootDir/$name" >/dev/null
    git fetch --depth=1 origin "$rev"
    git -c advice.detachedHead=false checkout "$rev"
    popd >/dev/null

    if [[ -f "build.mill" ]]; then
      patchMillRepo "build" "build.dependencies.$(pathToModule "$rootDir").$name"
    fi
    unset name url rev
  done

  echo "$rootDir"
}

if (( $_IS_EXEC )); then
  main
fi

# vim: ft=bash
