#!/usr/bin/env bash

set -e

PATH="$(nix build '.#mill-ivy-fetcher' --print-out-paths --no-link --max-jobs auto)/bin:$PATH"
PATH="$(nix build '.#mill' --print-out-paths --no-link)/bin:$PATH"

millHome=$(mktemp -d)
mif fetch --cache "$millHome"
mif codegen --cache "$millHome" -o ./script-lock.nix
