# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  arithmetic = {
    pname = "arithmetic";
    version = "2685fb7ec6dc7cca7ee3808377d841d19a9d2ced";
    src = fetchFromGitHub {
      owner = "sequencer";
      repo = "arithmetic";
      rev = "2685fb7ec6dc7cca7ee3808377d841d19a9d2ced";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-spc4SgYjc8PkVQXcV+Y4wmVxh6AFRGhLuhK3P359ngQ=";
    };
    date = "2023-11-06";
  };
  berkeley-hardfloat = {
    pname = "berkeley-hardfloat";
    version = "b3c8a38c286101973b3bc071f7918392343faba7";
    src = fetchFromGitHub {
      owner = "ucb-bar";
      repo = "berkeley-hardfloat";
      rev = "b3c8a38c286101973b3bc071f7918392343faba7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-VHOUFm5PM2ONxvE91tfxrsfPCRpsW/Ror1/giBiV9uo=";
    };
    date = "2023-10-25";
  };
  cde = {
    pname = "cde";
    version = "52768c97a27b254c0cc0ac9401feb55b29e18c28";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "cde";
      rev = "52768c97a27b254c0cc0ac9401feb55b29e18c28";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-wIj73zpdWveNMzXixd/dDkwsfoW/4IShdQxrXHLRkWs=";
    };
    date = "2023-08-05";
  };
  chisel = {
    pname = "chisel";
    version = "5d03a5cdd257f07a2a907cfb26a4dc26e4b65f2e";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel";
      rev = "5d03a5cdd257f07a2a907cfb26a4dc26e4b65f2e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-gZ43DFCEL4x+TI9WbgN2LJzpPdaSrLqJsDeq5nfKNSY=";
    };
    date = "2023-11-10";
  };
  rocket-chip = {
    pname = "rocket-chip";
    version = "1988d7d18ce366e4b48ffb41a9682faeed5303a5";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "rocket-chip";
      rev = "1988d7d18ce366e4b48ffb41a9682faeed5303a5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-0KaQcd2ZaFeCJV9KF2XFn+NC0fXZKzJxh0I8bsd21ig=";
    };
    date = "2023-11-08";
  };
  rocket-chip-inclusive-cache = {
    pname = "rocket-chip-inclusive-cache";
    version = "7f391c5e4cba3cdd4388efb778bd80da35d5574a";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "rocket-chip-inclusive-cache";
      rev = "7f391c5e4cba3cdd4388efb778bd80da35d5574a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-JP3DDuaqbACbG/wm/yWEaTYTT7pVj372YYrFk1tzpxM=";
    };
    date = "2023-08-15";
  };
  tilelink = {
    pname = "tilelink";
    version = "cd177e4636eb4a20326795a66e9ab502f9b2500a";
    src = fetchFromGitHub {
      owner = "sequencer";
      repo = "tilelink";
      rev = "cd177e4636eb4a20326795a66e9ab502f9b2500a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-+HJSdD9PaBh9cXIwIO902wKNOhbhp7IKax2hzdlhyps=";
    };
    date = "2023-08-11";
  };
}
