[package]
name = "online_vcs"
edition = "2021"
version.workspace = true

[lib]
crate-type = ["staticlib"]
name = "dpi"

[dependencies]
online_dpi = { path = "../online_dpi", features = ["svvpi"] }

[features]
trace = ["online_dpi/trace"]
