[arithmetic]
src.git = "https://github.com/sequencer/arithmetic"
src.branch = "master"
fetch.github = "sequencer/arithmetic"

[chisel]
src.git = "https://github.com/chipsalliance/chisel"
src.branch = "main"
fetch.github = "chipsalliance/chisel"

[chisel-interface]
src.git = "https://github.com/chipsalliance/chisel-interface"
src.branch = "master"
fetch.github = "chipsalliance/chisel-interface"

[rvdecoderdb]
src.git = "https://github.com/sequencer/rvdecoderdb"
src.branch = "master"
fetch.github = "sequencer/rvdecoderdb"

[riscv-opcodes]
src.git = "https://github.com/riscv/riscv-opcodes"
src.branch = "master"
fetch.github = "riscv/riscv-opcodes"

[zaozi]
src.git = "https://github.com/sequencer/zaozi"
src.branch = "master"
fetch.github = "sequencer/zaozi"
