= Introduction

The Pokedex project is an implementation of the RISC-V rv32imafc instruction
set architecture (ISA). It includes a formal specification, an instruction
decoder, and an emulator designed for functional verification.

A primary goal of this project is to provide a simple, maintainable, and
flexible design. This allows developers to easily add new instructions or make
architectural changes—capabilities not easily supported by existing tools like
riscv/sail-riscv or Spike (riscv/riscv-isa-sim).

The emulator can be linked with the T1 testbench to enable full functional
verification, including the standard RVV and custom extensions.

This guide explains the ASL (ARM Specification Language) model used in
the Pokedex project. It provides the necessary information for a developer to:

- Create functional model for RISC-V.
- Serve as a reference model for RTL design.
- Add custom instruction with low effort.

== Glossary

#table(
  columns: 2,
  [*Name*], [*Notes*],
  [*pokedex*], [
  Our T1 testbench works with a collection of micro-architecture designs, each
  of which is named after a Pokémon. We chose the name Pokedex for this project
  to align with that theme.

  In the world of Pokémon, a Pokédex is an essential tool for understanding the
  creatures you interact with. In the same spirit, this project provides the
  tools to help us better understand, maintain, and improve our T1
  architectures.
  ],

  [*ASL*], [
  ARM Specification Language (ASL) is an executable language for
  writing clear, precise specifications of Instruction Set Architectures
  (ISAs).
  ],

  [*ASLi*], [
  The ASL interpreter (ASLi) is an implementation of ASL that can execute ASL
  specifications either in an interpreter or by compiling via C code.
  ],
)

== How to build this document

Document are written in `docs/doc.typ` file. Developer should first install
typst and pandoc in their system environment.

- Build README

```bash
make doc
```

- Build PDF

```bash
make doc-pdf
```

== Resources

- ASL Document hosted by Intel Lab: https://intellabs.github.io/asl-interpreter/asl_reading.html
- ASL specification: https://developer.arm.com/documentation/ddi0626/latest

= Model design

== Instruction Sets
This section contains basic information of how to describe instruction semantics.

Instruction semantics are  are grouped by their instruction set.

== CSR
This section contains basic information of how to implement CSRs to models.

=== Reading and Writing CSRs
All Control and Status Register (CSR) operations are handled by two main APIs
that are generated by the codegen-cli tool.

- Read API: `func ReadCSR(csr_number: bits(12)) => bits(xlen)`
- Write API: `func WriteCSR(csr_number: bits(12), value: bits(xlen))`

The generated code works as a dispatcher. It uses pattern matching on the
`csr_number` parameter to identify the target CSR and then calls the
corresponding handler function that you have implemented for that specific
register.

For example, the generated code will look similar to this:

```asl
func ReadCSR(csr_number: bits(12)) => bits(32)
begin
  case csr_number of
    when '001_100_000_000' =>
      return ReadMstatus();
    when '001_100_000_001' =>
      return ReadMisa();
    // ...
    otherwise =>
      ThrowException(ExceptionType);
  end
end

func WriteCSR(csr_number: bits(12), value: bits(xlen))
begin
  case csr_number of
    when '001_100_000_000' =>
      WriteMstatus(value);
    when '001_100_000_001' =>
      WriteMisa(value);
    otherwise =>
      ThrowException(ExceptionType);
end
```

=== Implementing CSR Handlers
While the `codegen-cli` tool creates the main dispatcher and the function
signatures, developers are responsible for implementing the specific read and
write logic for each CSR.

This is done by providing the body of the function in a dedicated `.asl` file.
The build process then combines the provided logic with the generated function
signature.

Here is the step-by-step process to add a new CSR or modify an existing one.

*Step 1: Create the Handler Files*

The logic for each CSR operation lives in its own file. The `codegen-cli` tool
looks for these files in two directories:

- `csr/read/` for read operations.
- `csr/write/` for write operations.

The `codegen-cli` tool identifies each CSR and its corresponding address
directly from the `.asl` filename. This file-based mapping requires a strict
naming convention.

The required format is: `<csr_name>_<address>.asl`

- `<csr_name>`: The name of the CSR in lowercase (e.g., `mcycle`).
- `_`: An underscore used as a separator.
- `<address>`: The CSR address represented as a lowercase hexadecimal string,
  *without the `0x` prefix* (e.g., `b00` for address `0xB00`).

For example, to implement the `mcycle` CSR, you would create files named
`csr/read/mcycle_b00.asl` and `csr/write/mcycle_b00.asl`.

*Step 2: Implement the Handler Logic*

You only need to write the code that goes inside the function body. The tool
generates the function signature around your code.

*Read Handlers:*
The tool generates a read function named `Read<CsrName>`. Your `.asl` file in
the `csr/read/` directory must contain the logic to return the CSR's value as
`bits(xlen)` type.

*Write Handlers:*
The tool generates a write function named `Write<CsrName>`. Your `.asl` file in
the `csr/write/` directory must contain the logic to handle the write
operation. The new value is passed in as the `value` argument with `XLEN` bits.

==== Example: Implementing `misa`

Let's walk through the complete process for adding the `misa` (at `0x301`) CSR.

*1. Create the File Structure*

Create the empty `misa_301.asl` files in the correct directories. Your file
structure should look like this:
```
model/
└── csr/
    ├── csrs.csv
    ├── read/
    │   └── misa_301.asl
    └── write/
        └── misa_301.asl
```

*2. Implement the Read Logic (`read/misa_301.asl`)*

Add the CSR read logic to `csr/read/misa_301.asl`. This code snippet will become
the body of the `ReadMisa()` function.
```asl
// This logic assumes only rv32i is supported. The I-bit is controlled
// by the 'misa_i' register, and all other non-MXL bits are read-only-zero.

// Reports XLEN is 32
let mxl : bits(2) = '01';

// RO zero (4 bits) + Z to I (17 bits)
let ro_zero : bits(21) = Zeros(21);

// Assuming 'misa_i' is a global register defined elsewhere.
return [mxl, ro_zero, misa_i, '000', NOT(misa_i), '000'];
```

*3. Implement the Write Logic (`write/misa_301.asl`)*

Add the corresponding logic to `csr/write/misa_301.asl`. This becomes the body of
the `WriteMisa(value: bits(32))` function.
```asl
// The 'I' bit (bit 8) of MISA is the only writable bit in this example.
misa_i = value[8];
return TRUE;
```

*4. Final Generated Code*

After running `codegen-cli`, the tool will take your `.asl` snippets and
produce the following complete, callable functions:

```asl
func ReadMisa() => bits(32)
begin
  // This logic assumes only rv32i is supported. The I-bit is controlled
  // by the 'misa_i' register, and all other non-MXL bits are read-only-zero.

  // Reports XLEN is 32
  let mxl : bits(2) = '01';

  // RO zero (4 bits) + Z to I (17 bits)
  let ro_zero : bits(21) = Zeros(21);

  // Assuming 'misa_i' is a global register defined elsewhere.
  return [mxl, ro_zero, misa_i, '000', NOT(misa_i), '000'];
end

func WriteMisa(value : bits(32)) => boolean
begin
    // The 'I' bit (bit 8) of MISA is the only writable bit in this example.
    misa_i = value[8];
    return TRUE;
end
```
