# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  apache-33-pom = {
    pname = "apache-33-pom";
    version = "33";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/apache/apache/33/apache-33.pom";
      sha256 = "sha256-14vYUkxfg4ChkKZSVoZimpXf5RLfIRETg6bYwJI6RBU=";
    };
    install_path = "https/repo1.maven.org/maven2/org/apache/apache/33";
    pkgname = "apache";
  };
  "collections_2.13-1.10.7-bundle" = {
    pname = "collections_2.13-1.10.7-bundle";
    version = "1.10.7";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/collections_2.13/1.10.7/collections_2.13-1.10.7.jar";
      sha256 = "sha256-hZFhciTk9m7ipAxhkLZN5JbWPuKp4BuDWPxSlziyTDk=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/collections_2.13/1.10.7";
    pkgname = "collections_2.13";
  };
  "collections_2.13-1.10.7-pom" = {
    pname = "collections_2.13-1.10.7-pom";
    version = "1.10.7";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/collections_2.13/1.10.7/collections_2.13-1.10.7.pom";
      sha256 = "sha256-rOlIQmmpRLFAmO21KjzlCfUmrofZFVmALgzSQfHZ2UA=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/collections_2.13/1.10.7";
    pkgname = "collections_2.13";
  };
  "compiler-bridge_2.13-1.10.7-bundle" = {
    pname = "compiler-bridge_2.13-1.10.7-bundle";
    version = "1.10.7";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.13/1.10.7/compiler-bridge_2.13-1.10.7.jar";
      sha256 = "sha256-4ml4ho2EraIfc9JrPtR13ZYH5XB9KMqxTOsOqM7OEOI=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.13/1.10.7";
    pkgname = "compiler-bridge_2.13";
  };
  "compiler-bridge_2.13-1.10.7-pom" = {
    pname = "compiler-bridge_2.13-1.10.7-pom";
    version = "1.10.7";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.13/1.10.7/compiler-bridge_2.13-1.10.7.pom";
      sha256 = "sha256-tki5hhlGYh7dhgiXDaRDixibWPL/0uv/uU+GtSaDSPg=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.13/1.10.7";
    pkgname = "compiler-bridge_2.13";
  };
  "compiler-interface-1.10.3-bundle" = {
    pname = "compiler-interface-1.10.3-bundle";
    version = "1.10.3";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.10.3/compiler-interface-1.10.3.jar";
      sha256 = "sha256-12ZpOW3aLwNqNR1NRVxAur0//3/M0Rh76/xqMPK1+10=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.10.3";
    pkgname = "compiler-interface";
  };
  "compiler-interface-1.10.3-pom" = {
    pname = "compiler-interface-1.10.3-pom";
    version = "1.10.3";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.10.3/compiler-interface-1.10.3.pom";
      sha256 = "sha256-Ffe8HBunAu5qXvTbk6PRfSKphbJO1dQCQ5037ePcsP8=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.10.3";
    pkgname = "compiler-interface";
  };
  "compiler-interface-1.10.7-bundle" = {
    pname = "compiler-interface-1.10.7-bundle";
    version = "1.10.7";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.10.7/compiler-interface-1.10.7.jar";
      sha256 = "sha256-K6zFdh4DkgoijlydILM9nFHUOq8vUuj4OezmMJZuuIA=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.10.7";
    pkgname = "compiler-interface";
  };
  "compiler-interface-1.10.7-pom" = {
    pname = "compiler-interface-1.10.7-pom";
    version = "1.10.7";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.10.7/compiler-interface-1.10.7.pom";
      sha256 = "sha256-O3sNqL9YIKpQ9ESOGQId4RgxZPdKGAvQto59kvMATjE=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.10.7";
    pkgname = "compiler-interface";
  };
  "core-macros_2.13-1.10.7-bundle" = {
    pname = "core-macros_2.13-1.10.7-bundle";
    version = "1.10.7";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/core-macros_2.13/1.10.7/core-macros_2.13-1.10.7.jar";
      sha256 = "sha256-z96fLn2IXns+qBtUuMtXnxClmc8IAqBvGJkkP+4rIYk=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/core-macros_2.13/1.10.7";
    pkgname = "core-macros_2.13";
  };
  "core-macros_2.13-1.10.7-pom" = {
    pname = "core-macros_2.13-1.10.7-pom";
    version = "1.10.7";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/core-macros_2.13/1.10.7/core-macros_2.13-1.10.7.pom";
      sha256 = "sha256-liNQvw5uQXwF4VUoIrILMx2IbRgT2g6ThmkPVJe38Es=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/core-macros_2.13/1.10.7";
    pkgname = "core-macros_2.13";
  };
  "disruptor-3.4.2-bundle" = {
    pname = "disruptor-3.4.2-bundle";
    version = "3.4.2";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lmax/disruptor/3.4.2/disruptor-3.4.2.jar";
      sha256 = "sha256-9BLsuyNcJGC0XmNYQQlyPeqNlLgZx4yb/Dj1DLqFRsA=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lmax/disruptor/3.4.2";
    pkgname = "disruptor";
  };
  "disruptor-3.4.2-pom" = {
    pname = "disruptor-3.4.2-pom";
    version = "3.4.2";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lmax/disruptor/3.4.2/disruptor-3.4.2.pom";
      sha256 = "sha256-cxHl4mHKYvJZstFObW8c43WmRxhzGnMP187AIo1Q9do=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lmax/disruptor/3.4.2";
    pkgname = "disruptor";
  };
  "fansi_2.13-0.5.0-bundle" = {
    pname = "fansi_2.13-0.5.0-bundle";
    version = "0.5.0";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/fansi_2.13/0.5.0/fansi_2.13-0.5.0.jar";
      sha256 = "sha256-/K4mWA99bnKtvW5cUEuxcV++P1+4FNcOhLxUJ6g15Cw=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/fansi_2.13/0.5.0";
    pkgname = "fansi_2.13";
  };
  "fansi_2.13-0.5.0-pom" = {
    pname = "fansi_2.13-0.5.0-pom";
    version = "0.5.0";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/fansi_2.13/0.5.0/fansi_2.13-0.5.0.pom";
      sha256 = "sha256-TKF7Hlv3660AHWsvbCzVqcsuPlAmPPjlibjq5plrvo0=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/fansi_2.13/0.5.0";
    pkgname = "fansi_2.13";
  };
  "file-tree-views-2.1.12-bundle" = {
    pname = "file-tree-views-2.1.12-bundle";
    version = "2.1.12";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/swoval/file-tree-views/2.1.12/file-tree-views-2.1.12.jar";
      sha256 = "sha256-/XNziJt6ks8+l9s2ySC6JyrsFYqTh7Mln8qfLfrtqRQ=";
    };
    install_path = "https/repo1.maven.org/maven2/com/swoval/file-tree-views/2.1.12";
    pkgname = "file-tree-views";
  };
  "file-tree-views-2.1.12-pom" = {
    pname = "file-tree-views-2.1.12-pom";
    version = "2.1.12";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/swoval/file-tree-views/2.1.12/file-tree-views-2.1.12.pom";
      sha256 = "sha256-7dJw3HdtHYXdMA5BXP+eBgl1fXr+siOmsYe61bCr50Y=";
    };
    install_path = "https/repo1.maven.org/maven2/com/swoval/file-tree-views/2.1.12";
    pkgname = "file-tree-views";
  };
  "fusesource-pom-1.12-pom" = {
    pname = "fusesource-pom-1.12-pom";
    version = "1.12";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/fusesource/fusesource-pom/1.12/fusesource-pom-1.12.pom";
      sha256 = "sha256-xA2WDarc73sBwbHGZXr7rE//teUxaPj8sLKLhOb9zKE=";
    };
    install_path = "https/repo1.maven.org/maven2/org/fusesource/fusesource-pom/1.12";
    pkgname = "fusesource-pom";
  };
  "geny_2.13-1.0.0-bundle" = {
    pname = "geny_2.13-1.0.0-bundle";
    version = "1.0.0";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/geny_2.13/1.0.0/geny_2.13-1.0.0.jar";
      sha256 = "sha256-B4r1v0Bbv0HW7KZEGyvNKCVR0FTEes9PlJtsmDBjsRc=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/geny_2.13/1.0.0";
    pkgname = "geny_2.13";
  };
  "geny_2.13-1.0.0-pom" = {
    pname = "geny_2.13-1.0.0-pom";
    version = "1.0.0";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/geny_2.13/1.0.0/geny_2.13-1.0.0.pom";
      sha256 = "sha256-DXa85owFTshf7GhpT/rU+qYhKfC2R0Zr4gDLpB9DcNY=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/geny_2.13/1.0.0";
    pkgname = "geny_2.13";
  };
  "geny_2.13-1.1.0-bundle" = {
    pname = "geny_2.13-1.1.0-bundle";
    version = "1.1.0";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/geny_2.13/1.1.0/geny_2.13-1.1.0.jar";
      sha256 = "sha256-vZPyeAR7tTPacLQtKyHcKX2Ua6uGpP6ETCALTbjRdLU=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/geny_2.13/1.1.0";
    pkgname = "geny_2.13";
  };
  "geny_2.13-1.1.0-pom" = {
    pname = "geny_2.13-1.1.0-pom";
    version = "1.1.0";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/geny_2.13/1.1.0/geny_2.13-1.1.0.pom";
      sha256 = "sha256-Dl52rU8WvS+NE9yTbkZmVPKsVcdMawNuZ50yRDuhFCU=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/geny_2.13/1.1.0";
    pkgname = "geny_2.13";
  };
  "geny_2.13-1.1.1-bundle" = {
    pname = "geny_2.13-1.1.1-bundle";
    version = "1.1.1";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/geny_2.13/1.1.1/geny_2.13-1.1.1.jar";
      sha256 = "sha256-IK8jHCIvxxwp4Gs82NkZCha0EtqDzEn7C3eM8txvlNI=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/geny_2.13/1.1.1";
    pkgname = "geny_2.13";
  };
  "geny_2.13-1.1.1-pom" = {
    pname = "geny_2.13-1.1.1-pom";
    version = "1.1.1";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/geny_2.13/1.1.1/geny_2.13-1.1.1.pom";
      sha256 = "sha256-hI92BOaF6vKlsR84uLXeBpNKdp8+nRfAdyYEItMu01o=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/geny_2.13/1.1.1";
    pkgname = "geny_2.13";
  };
  "groovy-bom-4.0.22-pom" = {
    pname = "groovy-bom-4.0.22-pom";
    version = "4.0.22";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/apache/groovy/groovy-bom/4.0.22/groovy-bom-4.0.22.pom";
      sha256 = "sha256-Hh9rQiKue/1jMgA+33AgGDWZDb1GEGsWzduopT4832U=";
    };
    install_path = "https/repo1.maven.org/maven2/org/apache/groovy/groovy-bom/4.0.22";
    pkgname = "groovy-bom";
  };
  "io_2.13-1.10.3-bundle" = {
    pname = "io_2.13-1.10.3-bundle";
    version = "1.10.3";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/io_2.13/1.10.3/io_2.13-1.10.3.jar";
      sha256 = "sha256-JRtFEwfvrDJwVp+mGmostUNv36ZRxHf/wueaenq5ZHw=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/io_2.13/1.10.3";
    pkgname = "io_2.13";
  };
  "io_2.13-1.10.3-pom" = {
    pname = "io_2.13-1.10.3-pom";
    version = "1.10.3";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/io_2.13/1.10.3/io_2.13-1.10.3.pom";
      sha256 = "sha256-Nk9w4/HVu3de9JXV0XfTmGxxGlWxoDLRrlIXgkAMHMc=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/io_2.13/1.10.3";
    pkgname = "io_2.13";
  };
  "jackson-bom-2.17.2-pom" = {
    pname = "jackson-bom-2.17.2-pom";
    version = "2.17.2";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-bom/2.17.2/jackson-bom-2.17.2.pom";
      sha256 = "sha256-H0crC8IATVz0IaxIhxQX+EGJ5481wElxg4f9i0T7nzI=";
    };
    install_path = "https/repo1.maven.org/maven2/com/fasterxml/jackson/jackson-bom/2.17.2";
    pkgname = "jackson-bom";
  };
  "jackson-parent-2.17-pom" = {
    pname = "jackson-parent-2.17-pom";
    version = "2.17";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-parent/2.17/jackson-parent-2.17.pom";
      sha256 = "sha256-rubeSpcoOwQOQ/Ta1XXnt0eWzZhNiSdvfsdWc4DIop0=";
    };
    install_path = "https/repo1.maven.org/maven2/com/fasterxml/jackson/jackson-parent/2.17";
    pkgname = "jackson-parent";
  };
  "jakarta.jakartaee-bom-9.1.0-pom" = {
    pname = "jakarta.jakartaee-bom-9.1.0-pom";
    version = "9.1.0";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/jakarta/platform/jakarta.jakartaee-bom/9.1.0/jakarta.jakartaee-bom-9.1.0.pom";
      sha256 = "sha256-35jgJmIZ/buCVigm15o6IHdqi6Aqp4fw8HZaU4ZUyKQ=";
    };
    install_path = "https/repo1.maven.org/maven2/jakarta/platform/jakarta.jakartaee-bom/9.1.0";
    pkgname = "jakarta.jakartaee-bom";
  };
  "jakartaee-api-parent-9.1.0-pom" = {
    pname = "jakartaee-api-parent-9.1.0-pom";
    version = "9.1.0";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/jakarta/platform/jakartaee-api-parent/9.1.0/jakartaee-api-parent-9.1.0.pom";
      sha256 = "sha256-p3AsSHAmgCeEtXl7YjMKi41lkr8PRzeyXGel6sgmWcA=";
    };
    install_path = "https/repo1.maven.org/maven2/jakarta/platform/jakartaee-api-parent/9.1.0";
    pkgname = "jakartaee-api-parent";
  };
  "jansi-2.4.1-bundle" = {
    pname = "jansi-2.4.1-bundle";
    version = "2.4.1";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/2.4.1/jansi-2.4.1.jar";
      sha256 = "sha256-Ll53Wp3Fj/prvWqm8JnWL4ti3N60w8O7vlzyMBvC3ME=";
    };
    install_path = "https/repo1.maven.org/maven2/org/fusesource/jansi/jansi/2.4.1";
    pkgname = "jansi";
  };
  "jansi-2.4.1-pom" = {
    pname = "jansi-2.4.1-pom";
    version = "2.4.1";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/2.4.1/jansi-2.4.1.pom";
      sha256 = "sha256-P5jZeaTTVZ+HefuwBLNK51Fq+t9RDhHffMPNBz6xuzs=";
    };
    install_path = "https/repo1.maven.org/maven2/org/fusesource/jansi/jansi/2.4.1";
    pkgname = "jansi";
  };
  "java-diff-utils-4.12-bundle" = {
    pname = "java-diff-utils-4.12-bundle";
    version = "4.12";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/io/github/java-diff-utils/java-diff-utils/4.12/java-diff-utils-4.12.jar";
      sha256 = "sha256-mZCiA5d49rTMlHkBQcKGiGTqzuBiDGxFlFESGpAc1bU=";
    };
    install_path = "https/repo1.maven.org/maven2/io/github/java-diff-utils/java-diff-utils/4.12";
    pkgname = "java-diff-utils";
  };
  "java-diff-utils-4.12-pom" = {
    pname = "java-diff-utils-4.12-pom";
    version = "4.12";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/io/github/java-diff-utils/java-diff-utils/4.12/java-diff-utils-4.12.pom";
      sha256 = "sha256-wm4JftyOxoBdExmBfSPU5JbMEBXMVdxSAhEtj2qRZfw=";
    };
    install_path = "https/repo1.maven.org/maven2/io/github/java-diff-utils/java-diff-utils/4.12";
    pkgname = "java-diff-utils";
  };
  "java-diff-utils-parent-4.12-pom" = {
    pname = "java-diff-utils-parent-4.12-pom";
    version = "4.12";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/io/github/java-diff-utils/java-diff-utils-parent/4.12/java-diff-utils-parent-4.12.pom";
      sha256 = "sha256-2BHPnxGMwsrRMMlCetVcF01MCm8aAKwa4cm8vsXESxk=";
    };
    install_path = "https/repo1.maven.org/maven2/io/github/java-diff-utils/java-diff-utils-parent/4.12";
    pkgname = "java-diff-utils-parent";
  };
  "java-parent-pom-1.1.28-pom" = {
    pname = "java-parent-pom-1.1.28-pom";
    version = "1.1.28";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/net/openhft/java-parent-pom/1.1.28/java-parent-pom-1.1.28.pom";
      sha256 = "sha256-AhmcNHqdK55vXb+OE9TDTo/r+rkMm4H7oToW6CCICb8=";
    };
    install_path = "https/repo1.maven.org/maven2/net/openhft/java-parent-pom/1.1.28";
    pkgname = "java-parent-pom";
  };
  "jline-2.14.7-sbt-9a88bc413e2b34a4580c001c654d1a7f4f65bf18-bundle" = {
    pname = "jline-2.14.7-sbt-9a88bc413e2b34a4580c001c654d1a7f4f65bf18-bundle";
    version = "2.14.7-sbt-9a88bc413e2b34a4580c001c654d1a7f4f65bf18";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/jline/jline/2.14.7-sbt-9a88bc413e2b34a4580c001c654d1a7f4f65bf18/jline-2.14.7-sbt-9a88bc413e2b34a4580c001c654d1a7f4f65bf18.jar";
      sha256 = "sha256-oNuqeBlU+l7QFXBtEtAETgGKVwXaZ5HsmKUfs2XWbLA=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/jline/jline/2.14.7-sbt-9a88bc413e2b34a4580c001c654d1a7f4f65bf18";
    pkgname = "jline";
  };
  "jline-2.14.7-sbt-9a88bc413e2b34a4580c001c654d1a7f4f65bf18-pom" = {
    pname = "jline-2.14.7-sbt-9a88bc413e2b34a4580c001c654d1a7f4f65bf18-pom";
    version = "2.14.7-sbt-9a88bc413e2b34a4580c001c654d1a7f4f65bf18";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/jline/jline/2.14.7-sbt-9a88bc413e2b34a4580c001c654d1a7f4f65bf18/jline-2.14.7-sbt-9a88bc413e2b34a4580c001c654d1a7f4f65bf18.pom";
      sha256 = "sha256-fiebiHtNMNGo1Ntlffaobq1Pj07msv/dALQX6vgJ8yU=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/jline/jline/2.14.7-sbt-9a88bc413e2b34a4580c001c654d1a7f4f65bf18";
    pkgname = "jline";
  };
  "jline-3.26.3-bundle" = {
    pname = "jline-3.26.3-bundle";
    version = "3.26.3";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/jline/jline/3.26.3/jline-3.26.3.jar";
      sha256 = "sha256-8jEWw0kxRljN66psr20AZ3M8yeW4UsrSop5kPTK9Ur0=";
    };
    install_path = "https/repo1.maven.org/maven2/org/jline/jline/3.26.3";
    pkgname = "jline";
  };
  "jline-3.26.3-pom" = {
    pname = "jline-3.26.3-pom";
    version = "3.26.3";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/jline/jline/3.26.3/jline-3.26.3.pom";
      sha256 = "sha256-qvtXBPA+JK/9NnaKNdbE9blcB3nxNvDnjB5GO+ltkKI=";
    };
    install_path = "https/repo1.maven.org/maven2/org/jline/jline/3.26.3";
    pkgname = "jline";
  };
  "jline-native-3.27.1-bundle" = {
    pname = "jline-native-3.27.1-bundle";
    version = "3.27.1";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/jline/jline-native/3.27.1/jline-native-3.27.1.jar";
      sha256 = "sha256-Y2ZG2kBBPnSWOz9LQMnF3PtC89Ds8bk9bd9ciV7/5CI=";
    };
    install_path = "https/repo1.maven.org/maven2/org/jline/jline-native/3.27.1";
    pkgname = "jline-native";
  };
  "jline-native-3.27.1-pom" = {
    pname = "jline-native-3.27.1-pom";
    version = "3.27.1";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/jline/jline-native/3.27.1/jline-native-3.27.1.pom";
      sha256 = "sha256-n/4orsyfVG7JaV8tUh9nRZtLNpFxSMCNFvRVazg9Mo8=";
    };
    install_path = "https/repo1.maven.org/maven2/org/jline/jline-native/3.27.1";
    pkgname = "jline-native";
  };
  "jline-parent-3.27.1-pom" = {
    pname = "jline-parent-3.27.1-pom";
    version = "3.27.1";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/jline/jline-parent/3.27.1/jline-parent-3.27.1.pom";
      sha256 = "sha256-6WT9B2wgziTdtI3XN6CNYFA0cAXj5u7IL/XrBD1WFYE=";
    };
    install_path = "https/repo1.maven.org/maven2/org/jline/jline-parent/3.27.1";
    pkgname = "jline-parent";
  };
  "jline-terminal-3.27.1-bundle" = {
    pname = "jline-terminal-3.27.1-bundle";
    version = "3.27.1";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/jline/jline-terminal/3.27.1/jline-terminal-3.27.1.jar";
      sha256 = "sha256-Qre3VlBrypi1BZOEJqNcmQgveBnDM+0lvUEUv7DjtfI=";
    };
    install_path = "https/repo1.maven.org/maven2/org/jline/jline-terminal/3.27.1";
    pkgname = "jline-terminal";
  };
  "jline-terminal-3.27.1-pom" = {
    pname = "jline-terminal-3.27.1-pom";
    version = "3.27.1";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/jline/jline-terminal/3.27.1/jline-terminal-3.27.1.pom";
      sha256 = "sha256-hHjnmqIupq95eWRD+O0w//pdxkfrPS0YYLrC4j800pc=";
    };
    install_path = "https/repo1.maven.org/maven2/org/jline/jline-terminal/3.27.1";
    pkgname = "jline-terminal";
  };
  "jline-terminal-jni-3.27.1-bundle" = {
    pname = "jline-terminal-jni-3.27.1-bundle";
    version = "3.27.1";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/jline/jline-terminal-jni/3.27.1/jline-terminal-jni-3.27.1.jar";
      sha256 = "sha256-5Lxk8eaOn7JdgFFzOOdqvKHgFFuC44m1wrLH1x0VD4I=";
    };
    install_path = "https/repo1.maven.org/maven2/org/jline/jline-terminal-jni/3.27.1";
    pkgname = "jline-terminal-jni";
  };
  "jline-terminal-jni-3.27.1-pom" = {
    pname = "jline-terminal-jni-3.27.1-pom";
    version = "3.27.1";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/jline/jline-terminal-jni/3.27.1/jline-terminal-jni-3.27.1.pom";
      sha256 = "sha256-UkSN48v1X4BwFITLSiO1jLGw2P6qhtvdwyE2ByQ2l1c=";
    };
    install_path = "https/repo1.maven.org/maven2/org/jline/jline-terminal-jni/3.27.1";
    pkgname = "jline-terminal-jni";
  };
  "jna-5.14.0-bundle" = {
    pname = "jna-5.14.0-bundle";
    version = "5.14.0";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/net/java/dev/jna/jna/5.14.0/jna-5.14.0.jar";
      sha256 = "sha256-NO0eHyf6iWvKUNvE6ZzzcylnzsOHp6DV40hsCWc/6MY=";
    };
    install_path = "https/repo1.maven.org/maven2/net/java/dev/jna/jna/5.14.0";
    pkgname = "jna";
  };
  "jna-5.14.0-pom" = {
    pname = "jna-5.14.0-pom";
    version = "5.14.0";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/net/java/dev/jna/jna/5.14.0/jna-5.14.0.pom";
      sha256 = "sha256-4E4llRUB3yWtx7Hc22xTNzyUiXuE0+FJISknY+4Hrj0=";
    };
    install_path = "https/repo1.maven.org/maven2/net/java/dev/jna/jna/5.14.0";
    pkgname = "jna";
  };
  "junit-bom-5.10.3-pom" = {
    pname = "junit-bom-5.10.3-pom";
    version = "5.10.3";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/junit/junit-bom/5.10.3/junit-bom-5.10.3.pom";
      sha256 = "sha256-EJN9RMQlmEy4c5Il00cS4aMUVkHKk6w/fvGG+iX2urw=";
    };
    install_path = "https/repo1.maven.org/maven2/org/junit/junit-bom/5.10.3";
    pkgname = "junit-bom";
  };
  "launcher-interface-1.4.4-bundle" = {
    pname = "launcher-interface-1.4.4-bundle";
    version = "1.4.4";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/launcher-interface/1.4.4/launcher-interface-1.4.4.jar";
      sha256 = "sha256-rrW8E07NN8pVMv0mML5lBYuI/X3RxRfLS1LTFrUr4s4=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/launcher-interface/1.4.4";
    pkgname = "launcher-interface";
  };
  "launcher-interface-1.4.4-pom" = {
    pname = "launcher-interface-1.4.4-pom";
    version = "1.4.4";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/launcher-interface/1.4.4/launcher-interface-1.4.4.pom";
      sha256 = "sha256-4ln1ERKUVnfDcSzHAQGPb2ZGMKSTGXx9LXtcOyCRotQ=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/launcher-interface/1.4.4";
    pkgname = "launcher-interface";
  };
  "log4j-2.24.3-pom" = {
    pname = "log4j-2.24.3-pom";
    version = "2.24.3";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j/2.24.3/log4j-2.24.3.pom";
      sha256 = "sha256-wUG0hj/AzqtYOJShPh+eUsAfwtdYcn1nR/a5nVBA87E=";
    };
    install_path = "https/repo1.maven.org/maven2/org/apache/logging/log4j/log4j/2.24.3";
    pkgname = "log4j";
  };
  "log4j-api-2.24.3-bundle" = {
    pname = "log4j-api-2.24.3-bundle";
    version = "2.24.3";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-api/2.24.3/log4j-api-2.24.3.jar";
      sha256 = "sha256-W0oKDNDnUd7UMcFiRCvb3VMyjR+Lsrrl/Bu+7g9m2A8=";
    };
    install_path = "https/repo1.maven.org/maven2/org/apache/logging/log4j/log4j-api/2.24.3";
    pkgname = "log4j-api";
  };
  "log4j-api-2.24.3-pom" = {
    pname = "log4j-api-2.24.3-pom";
    version = "2.24.3";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-api/2.24.3/log4j-api-2.24.3.pom";
      sha256 = "sha256-vAXeM1M6Elmtusv8yCbNZjdqLZxO5T+4NgCfRKRbgjk=";
    };
    install_path = "https/repo1.maven.org/maven2/org/apache/logging/log4j/log4j-api/2.24.3";
    pkgname = "log4j-api";
  };
  "log4j-bom-2.24.3-pom" = {
    pname = "log4j-bom-2.24.3-pom";
    version = "2.24.3";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-bom/2.24.3/log4j-bom-2.24.3.pom";
      sha256 = "sha256-sXq38yj0WGt+cfjJT8NaXaK86AcFpdYwBAIsGSiDNVg=";
    };
    install_path = "https/repo1.maven.org/maven2/org/apache/logging/log4j/log4j-bom/2.24.3";
    pkgname = "log4j-bom";
  };
  "log4j-core-2.24.3-bundle" = {
    pname = "log4j-core-2.24.3-bundle";
    version = "2.24.3";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.24.3/log4j-core-2.24.3.jar";
      sha256 = "sha256-frQIRZauJb08YWmOSOjQq2WpJgdYiE7Vy7nG5VxEpWo=";
    };
    install_path = "https/repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.24.3";
    pkgname = "log4j-core";
  };
  "log4j-core-2.24.3-pom" = {
    pname = "log4j-core-2.24.3-pom";
    version = "2.24.3";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.24.3/log4j-core-2.24.3.pom";
      sha256 = "sha256-v9XAxKrGECQsy2H/ABCK1zeA2iCi9ym+Bjg2qXZXf1c=";
    };
    install_path = "https/repo1.maven.org/maven2/org/apache/logging/log4j/log4j-core/2.24.3";
    pkgname = "log4j-core";
  };
  "logging-parent-11.3.0-pom" = {
    pname = "logging-parent-11.3.0-pom";
    version = "11.3.0";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/apache/logging/logging-parent/11.3.0/logging-parent-11.3.0.pom";
      sha256 = "sha256-pcmFtW/hxYQzOTtQkabznlufeFGN2PySE0aQWZtk19A=";
    };
    install_path = "https/repo1.maven.org/maven2/org/apache/logging/logging-parent/11.3.0";
    pkgname = "logging-parent";
  };
  "mainargs_2.13-0.7.6-bundle" = {
    pname = "mainargs_2.13-0.7.6-bundle";
    version = "0.7.6";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/mainargs_2.13/0.7.6/mainargs_2.13-0.7.6.jar";
      sha256 = "sha256-ujbt3LWyAbYgYjv/e67FJwU3FoYtPStzoceIMxye/d0=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/mainargs_2.13/0.7.6";
    pkgname = "mainargs_2.13";
  };
  "mainargs_2.13-0.7.6-pom" = {
    pname = "mainargs_2.13-0.7.6-pom";
    version = "0.7.6";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/mainargs_2.13/0.7.6/mainargs_2.13-0.7.6.pom";
      sha256 = "sha256-yrYbZn32G3CvWgYAI+R5LWDpbK4ngIVcoNtK6YpUqqc=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/mainargs_2.13/0.7.6";
    pkgname = "mainargs_2.13";
  };
  "mill-main-api_2.13-0.12.8-1-46e216-bundle" = {
    pname = "mill-main-api_2.13-0.12.8-1-46e216-bundle";
    version = "0.12.8-1-46e216";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/mill-main-api_2.13/0.12.8-1-46e216/mill-main-api_2.13-0.12.8-1-46e216.jar";
      sha256 = "sha256-zwDvA8zhhsX0r6I7SnJbAVnPhwew3Lie9R8oo6fcXBc=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/mill-main-api_2.13/0.12.8-1-46e216";
    pkgname = "mill-main-api_2.13";
  };
  "mill-main-api_2.13-0.12.8-1-46e216-pom" = {
    pname = "mill-main-api_2.13-0.12.8-1-46e216-pom";
    version = "0.12.8-1-46e216";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/mill-main-api_2.13/0.12.8-1-46e216/mill-main-api_2.13-0.12.8-1-46e216.pom";
      sha256 = "sha256-0uVPZh9QHqsy5Z1omq+0dn4pGNIQQ1neXStC237e4kQ=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/mill-main-api_2.13/0.12.8-1-46e216";
    pkgname = "mill-main-api_2.13";
  };
  "mill-main-client-0.12.8-1-46e216-bundle" = {
    pname = "mill-main-client-0.12.8-1-46e216-bundle";
    version = "0.12.8-1-46e216";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/mill-main-client/0.12.8-1-46e216/mill-main-client-0.12.8-1-46e216.jar";
      sha256 = "sha256-iqsuuohoTyPDIkwpatWJsHtJwZSVxMXnzW/ltsknd8M=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/mill-main-client/0.12.8-1-46e216";
    pkgname = "mill-main-client";
  };
  "mill-main-client-0.12.8-1-46e216-pom" = {
    pname = "mill-main-client-0.12.8-1-46e216-pom";
    version = "0.12.8-1-46e216";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/mill-main-client/0.12.8-1-46e216/mill-main-client-0.12.8-1-46e216.pom";
      sha256 = "sha256-u7w6bWqAK0au8sbVnYpp4ANXJHV0ktEIrV8O9r/Rxo4=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/mill-main-client/0.12.8-1-46e216";
    pkgname = "mill-main-client";
  };
  "mill-moduledefs_2.13-0.11.2-bundle" = {
    pname = "mill-moduledefs_2.13-0.11.2-bundle";
    version = "0.11.2";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/mill-moduledefs_2.13/0.11.2/mill-moduledefs_2.13-0.11.2.jar";
      sha256 = "sha256-5+5vmebD4i37cup1wI0koEc/zM3TRu0LOeWIjrYYxM4=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/mill-moduledefs_2.13/0.11.2";
    pkgname = "mill-moduledefs_2.13";
  };
  "mill-moduledefs_2.13-0.11.2-pom" = {
    pname = "mill-moduledefs_2.13-0.11.2-pom";
    version = "0.11.2";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/mill-moduledefs_2.13/0.11.2/mill-moduledefs_2.13-0.11.2.pom";
      sha256 = "sha256-SBOavgguoUyVsBHRRpwiyxpJ6OpbF5i5HHnsG5UhwNI=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/mill-moduledefs_2.13/0.11.2";
    pkgname = "mill-moduledefs_2.13";
  };
  "mill-runner-linenumbers_2.13-0.12.8-1-46e216-bundle" = {
    pname = "mill-runner-linenumbers_2.13-0.12.8-1-46e216-bundle";
    version = "0.12.8-1-46e216";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/mill-runner-linenumbers_2.13/0.12.8-1-46e216/mill-runner-linenumbers_2.13-0.12.8-1-46e216.jar";
      sha256 = "sha256-GSLf0Md+qUAqroPFaBeMOimLtm2oKlK2ix/rSK7h2pU=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/mill-runner-linenumbers_2.13/0.12.8-1-46e216";
    pkgname = "mill-runner-linenumbers_2.13";
  };
  "mill-runner-linenumbers_2.13-0.12.8-1-46e216-pom" = {
    pname = "mill-runner-linenumbers_2.13-0.12.8-1-46e216-pom";
    version = "0.12.8-1-46e216";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/mill-runner-linenumbers_2.13/0.12.8-1-46e216/mill-runner-linenumbers_2.13-0.12.8-1-46e216.pom";
      sha256 = "sha256-rKkvS7+5ulEBAQB3ccyL2J3k/EqbtHCnPkc3Oottm20=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/mill-runner-linenumbers_2.13/0.12.8-1-46e216";
    pkgname = "mill-runner-linenumbers_2.13";
  };
  "mill-scala-compiler-bridge_2.13.15-0.0.1-bundle" = {
    pname = "mill-scala-compiler-bridge_2.13.15-0.0.1-bundle";
    version = "0.0.1";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/mill-scala-compiler-bridge_2.13.15/0.0.1/mill-scala-compiler-bridge_2.13.15-0.0.1.jar";
      sha256 = "sha256-mf2hc4LBMaJ+uqpcHZVhM0+YfzeJnEbwVcDSWL81n2s=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/mill-scala-compiler-bridge_2.13.15/0.0.1";
    pkgname = "mill-scala-compiler-bridge_2.13.15";
  };
  "mill-scala-compiler-bridge_2.13.15-0.0.1-pom" = {
    pname = "mill-scala-compiler-bridge_2.13.15-0.0.1-pom";
    version = "0.0.1";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/mill-scala-compiler-bridge_2.13.15/0.0.1/mill-scala-compiler-bridge_2.13.15-0.0.1.pom";
      sha256 = "sha256-+Z5Tlk1ZRoOxqeNvX0vfXSkbXQR7blXRJhfSuXpEbjA=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/mill-scala-compiler-bridge_2.13.15/0.0.1";
    pkgname = "mill-scala-compiler-bridge_2.13.15";
  };
  "mill-scalalib-api_2.13-0.12.8-1-46e216-bundle" = {
    pname = "mill-scalalib-api_2.13-0.12.8-1-46e216-bundle";
    version = "0.12.8-1-46e216";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/mill-scalalib-api_2.13/0.12.8-1-46e216/mill-scalalib-api_2.13-0.12.8-1-46e216.jar";
      sha256 = "sha256-9J3HpmpOjBFEtJCHncAWDxiNocwBykzgXaQTFCUVubw=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/mill-scalalib-api_2.13/0.12.8-1-46e216";
    pkgname = "mill-scalalib-api_2.13";
  };
  "mill-scalalib-api_2.13-0.12.8-1-46e216-pom" = {
    pname = "mill-scalalib-api_2.13-0.12.8-1-46e216-pom";
    version = "0.12.8-1-46e216";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/mill-scalalib-api_2.13/0.12.8-1-46e216/mill-scalalib-api_2.13-0.12.8-1-46e216.pom";
      sha256 = "sha256-oFESy0rM9xj7NjAxHpvZApjAsFgwOV24QTGZLH9p06I=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/mill-scalalib-api_2.13/0.12.8-1-46e216";
    pkgname = "mill-scalalib-api_2.13";
  };
  "mill-scalalib-worker_2.13-0.12.8-1-46e216-bundle" = {
    pname = "mill-scalalib-worker_2.13-0.12.8-1-46e216-bundle";
    version = "0.12.8-1-46e216";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/mill-scalalib-worker_2.13/0.12.8-1-46e216/mill-scalalib-worker_2.13-0.12.8-1-46e216.jar";
      sha256 = "sha256-mD8rzZnIeo+mgpVRQdWGzMotbuDE7sRtlrP5dWi8ObY=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/mill-scalalib-worker_2.13/0.12.8-1-46e216";
    pkgname = "mill-scalalib-worker_2.13";
  };
  "mill-scalalib-worker_2.13-0.12.8-1-46e216-pom" = {
    pname = "mill-scalalib-worker_2.13-0.12.8-1-46e216-pom";
    version = "0.12.8-1-46e216";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/mill-scalalib-worker_2.13/0.12.8-1-46e216/mill-scalalib-worker_2.13-0.12.8-1-46e216.pom";
      sha256 = "sha256-xLqKNp0oA1FPXd9xHcGNg84a2CJfk+xF5iFbXcChc1I=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/mill-scalalib-worker_2.13/0.12.8-1-46e216";
    pkgname = "mill-scalalib-worker_2.13";
  };
  "mockito-bom-4.11.0-pom" = {
    pname = "mockito-bom-4.11.0-pom";
    version = "4.11.0";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/mockito/mockito-bom/4.11.0/mockito-bom-4.11.0.pom";
      sha256 = "sha256-2FMadGyYj39o7V8YjN6pRQBq6pk+xd+eUk4NJ9YUkdo=";
    };
    install_path = "https/repo1.maven.org/maven2/org/mockito/mockito-bom/4.11.0";
    pkgname = "mockito-bom";
  };
  "os-lib_2.13-0.11.4-M6-bundle" = {
    pname = "os-lib_2.13-0.11.4-M6-bundle";
    version = "0.11.4-M6";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/os-lib_2.13/0.11.4-M6/os-lib_2.13-0.11.4-M6.jar";
      sha256 = "sha256-zhzOZEjTMyfsfrLRLdHCLZgQohocv3aPOwNjBNImpIA=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/os-lib_2.13/0.11.4-M6";
    pkgname = "os-lib_2.13";
  };
  "os-lib_2.13-0.11.4-M6-pom" = {
    pname = "os-lib_2.13-0.11.4-M6-pom";
    version = "0.11.4-M6";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/os-lib_2.13/0.11.4-M6/os-lib_2.13-0.11.4-M6.pom";
      sha256 = "sha256-kHXouAKqYiPODZQ0760R07a4n8w3S9qOmUh1/TgGAU8=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/os-lib_2.13/0.11.4-M6";
    pkgname = "os-lib_2.13";
  };
  "os-lib_2.13-0.9.1-bundle" = {
    pname = "os-lib_2.13-0.9.1-bundle";
    version = "0.9.1";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/os-lib_2.13/0.9.1/os-lib_2.13-0.9.1.jar";
      sha256 = "sha256-7DKIhkOrJym9mpAFmXaJRrNTFwkT2HZdR2pj2QxKkoc=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/os-lib_2.13/0.9.1";
    pkgname = "os-lib_2.13";
  };
  "os-lib_2.13-0.9.1-pom" = {
    pname = "os-lib_2.13-0.9.1-pom";
    version = "0.9.1";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/os-lib_2.13/0.9.1/os-lib_2.13-0.9.1.pom";
      sha256 = "sha256-/PDrFRMCMOX3jdVLiyWp0c7y4JHh0WtE7H8cnu9asQY=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/os-lib_2.13/0.9.1";
    pkgname = "os-lib_2.13";
  };
  oss-parent-58-pom = {
    pname = "oss-parent-58-pom";
    version = "58";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/fasterxml/oss-parent/58/oss-parent-58.pom";
      sha256 = "sha256-VnDmrBxN3MnUE8+HmXpdou+qTSq+Q5Njr57xAqCgnkA=";
    };
    install_path = "https/repo1.maven.org/maven2/com/fasterxml/oss-parent/58";
    pkgname = "oss-parent";
  };
  "pprint_2.13-0.9.0-bundle" = {
    pname = "pprint_2.13-0.9.0-bundle";
    version = "0.9.0";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/pprint_2.13/0.9.0/pprint_2.13-0.9.0.jar";
      sha256 = "sha256-XdNrZa3c1HvMxo023QC+6T4t70OfGjbQKkUDCOjZo9M=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/pprint_2.13/0.9.0";
    pkgname = "pprint_2.13";
  };
  "pprint_2.13-0.9.0-pom" = {
    pname = "pprint_2.13-0.9.0-pom";
    version = "0.9.0";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/pprint_2.13/0.9.0/pprint_2.13-0.9.0.pom";
      sha256 = "sha256-8MEu42PW11u42Pqjedk2ebTwxtYcyWtPykxM3yO5isQ=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/pprint_2.13/0.9.0";
    pkgname = "pprint_2.13";
  };
  "project-1.0.7-pom" = {
    pname = "project-1.0.7-pom";
    version = "1.0.7";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/eclipse/ee4j/project/1.0.7/project-1.0.7.pom";
      sha256 = "sha256-IFwDmkLLrjVW776wSkg+s6PPlVC9db+EJg3I8oIY8QU=";
    };
    install_path = "https/repo1.maven.org/maven2/org/eclipse/ee4j/project/1.0.7";
    pkgname = "project";
  };
  "root-parent-pom-1.2.12-pom" = {
    pname = "root-parent-pom-1.2.12-pom";
    version = "1.2.12";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/net/openhft/root-parent-pom/1.2.12/root-parent-pom-1.2.12.pom";
      sha256 = "sha256-MYArTIZCLZGsUzfa1wURNTXKmG9817wjlwG5+d+WfM8=";
    };
    install_path = "https/repo1.maven.org/maven2/net/openhft/root-parent-pom/1.2.12";
    pkgname = "root-parent-pom";
  };
  "sbinary_2.13-0.5.1-bundle" = {
    pname = "sbinary_2.13-0.5.1-bundle";
    version = "0.5.1";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/sbinary_2.13/0.5.1/sbinary_2.13-0.5.1.jar";
      sha256 = "sha256-Kf/dtVRxkQ8sX4KpVGg84fqzsJSQC5etsfd3xEsa/Mw=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/sbinary_2.13/0.5.1";
    pkgname = "sbinary_2.13";
  };
  "sbinary_2.13-0.5.1-pom" = {
    pname = "sbinary_2.13-0.5.1-pom";
    version = "0.5.1";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/sbinary_2.13/0.5.1/sbinary_2.13-0.5.1.pom";
      sha256 = "sha256-dX4cy3163XqY7ZdZaJOEeYjoYtlS4SXSnla7lMtJlJs=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/sbinary_2.13/0.5.1";
    pkgname = "sbinary_2.13";
  };
  "scala-collection-compat_2.13-2.12.0-bundle" = {
    pname = "scala-collection-compat_2.13-2.12.0-bundle";
    version = "2.12.0";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.13/2.12.0/scala-collection-compat_2.13-2.12.0.jar";
      sha256 = "sha256-vv/0giM81/mnyh4fWjbt5CHAGObOgjWJeMR11FUydV8=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.13/2.12.0";
    pkgname = "scala-collection-compat_2.13";
  };
  "scala-collection-compat_2.13-2.12.0-pom" = {
    pname = "scala-collection-compat_2.13-2.12.0-pom";
    version = "2.12.0";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.13/2.12.0/scala-collection-compat_2.13-2.12.0.pom";
      sha256 = "sha256-tSMCkiCYLivduDPSlYWSvTfSdxPvH7uzGl7wba/9/LQ=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.13/2.12.0";
    pkgname = "scala-collection-compat_2.13";
  };
  "scala-compiler-2.13.15-bundle" = {
    pname = "scala-compiler-2.13.15-bundle";
    version = "2.13.15";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.15/scala-compiler-2.13.15.jar";
      sha256 = "sha256-TCAM0ZPAgr7BSiot/+ahul+BMLGyfHnuVMk238r8jtk=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.15";
    pkgname = "scala-compiler";
  };
  "scala-compiler-2.13.15-pom" = {
    pname = "scala-compiler-2.13.15-pom";
    version = "2.13.15";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.15/scala-compiler-2.13.15.pom";
      sha256 = "sha256-auEwgelQpVVF5T5+b5v2dU7Q7BevMxdyro+uT7QG9pc=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.15";
    pkgname = "scala-compiler";
  };
  "scala-library-2.13.15-bundle" = {
    pname = "scala-library-2.13.15-bundle";
    version = "2.13.15";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.15/scala-library-2.13.15.jar";
      sha256 = "sha256-jk28O+z3DVnHhxGPatBvq2eQE2oGmc1kErydo9M2lE4=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.15";
    pkgname = "scala-library";
  };
  "scala-library-2.13.15-pom" = {
    pname = "scala-library-2.13.15-pom";
    version = "2.13.15";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.15/scala-library-2.13.15.pom";
      sha256 = "sha256-+B1vMpF6DpMdqmVZqFAL4cYv+MbILbBx3Nvr9gu9R4Y=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.15";
    pkgname = "scala-library";
  };
  "scala-parallel-collections_2.13-0.2.0-bundle" = {
    pname = "scala-parallel-collections_2.13-0.2.0-bundle";
    version = "0.2.0";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parallel-collections_2.13/0.2.0/scala-parallel-collections_2.13-0.2.0.jar";
      sha256 = "sha256-0V8i8TCLmOmsUqPRrI1YLVSNbYUrERbL31pQ9DEkbtE=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-lang/modules/scala-parallel-collections_2.13/0.2.0";
    pkgname = "scala-parallel-collections_2.13";
  };
  "scala-parallel-collections_2.13-0.2.0-pom" = {
    pname = "scala-parallel-collections_2.13-0.2.0-pom";
    version = "0.2.0";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parallel-collections_2.13/0.2.0/scala-parallel-collections_2.13-0.2.0.pom";
      sha256 = "sha256-KpXuHbIOpnF42bQrTOCbFHIjqj7qmSxz8mKttclzORk=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-lang/modules/scala-parallel-collections_2.13/0.2.0";
    pkgname = "scala-parallel-collections_2.13";
  };
  "scala-parser-combinators_2.13-1.1.2-bundle" = {
    pname = "scala-parser-combinators_2.13-1.1.2-bundle";
    version = "1.1.2";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.13/1.1.2/scala-parser-combinators_2.13-1.1.2.jar";
      sha256 = "sha256-XChbcubcCpjpmuChzutAJ9q5rfpEGEQEa9Pxng79y1Q=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.13/1.1.2";
    pkgname = "scala-parser-combinators_2.13";
  };
  "scala-parser-combinators_2.13-1.1.2-pom" = {
    pname = "scala-parser-combinators_2.13-1.1.2-pom";
    version = "1.1.2";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.13/1.1.2/scala-parser-combinators_2.13-1.1.2.pom";
      sha256 = "sha256-XIVv78BGqI3gEYrF5Fzd9jiXX6mAwAfSQmMydvcmbwI=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.13/1.1.2";
    pkgname = "scala-parser-combinators_2.13";
  };
  "scala-reflect-2.13.15-bundle" = {
    pname = "scala-reflect-2.13.15-bundle";
    version = "2.13.15";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.15/scala-reflect-2.13.15.jar";
      sha256 = "sha256-eNDMNQ4e5C2HxuEc9bDce/C3CCnACqOPJ7+wGdQ53BE=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.15";
    pkgname = "scala-reflect";
  };
  "scala-reflect-2.13.15-pom" = {
    pname = "scala-reflect-2.13.15-pom";
    version = "2.13.15";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.15/scala-reflect-2.13.15.pom";
      sha256 = "sha256-qpysWTJIJOXnPcNFb9PDq19QTfY9Lx3bZBN4Orsc7NY=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.15";
    pkgname = "scala-reflect";
  };
  "scala-xml_2.13-2.3.0-bundle" = {
    pname = "scala-xml_2.13-2.3.0-bundle";
    version = "2.3.0";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.13/2.3.0/scala-xml_2.13-2.3.0.jar";
      sha256 = "sha256-S01mmMdL/4ShBRArv1g5CYDce7jEC96kvHJwQLP5Zr0=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.13/2.3.0";
    pkgname = "scala-xml_2.13";
  };
  "scala-xml_2.13-2.3.0-pom" = {
    pname = "scala-xml_2.13-2.3.0-pom";
    version = "2.3.0";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.13/2.3.0/scala-xml_2.13-2.3.0.pom";
      sha256 = "sha256-nlKx4JOFPhRrC3VgWvmFQyGRk8rU6lDQe5RGX0r6gVw=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.13/2.3.0";
    pkgname = "scala-xml_2.13";
  };
  "scalac-mill-moduledefs-plugin_2.13.15-0.11.2-bundle" = {
    pname = "scalac-mill-moduledefs-plugin_2.13.15-0.11.2-bundle";
    version = "0.11.2";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/scalac-mill-moduledefs-plugin_2.13.15/0.11.2/scalac-mill-moduledefs-plugin_2.13.15-0.11.2.jar";
      sha256 = "sha256-PXciFheEOrB1J4ftu62h8FSGjZSjb6k38ecFxf8opGE=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/scalac-mill-moduledefs-plugin_2.13.15/0.11.2";
    pkgname = "scalac-mill-moduledefs-plugin_2.13.15";
  };
  "scalac-mill-moduledefs-plugin_2.13.15-0.11.2-pom" = {
    pname = "scalac-mill-moduledefs-plugin_2.13.15-0.11.2-pom";
    version = "0.11.2";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/scalac-mill-moduledefs-plugin_2.13.15/0.11.2/scalac-mill-moduledefs-plugin_2.13.15-0.11.2.pom";
      sha256 = "sha256-iQf2G6M9oLGJHrJj8Cgtdlnyv2MCW1SEzZEVVPNzmd8=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/scalac-mill-moduledefs-plugin_2.13.15/0.11.2";
    pkgname = "scalac-mill-moduledefs-plugin_2.13.15";
  };
  "scalap-2.13.15-bundle" = {
    pname = "scalap-2.13.15-bundle";
    version = "2.13.15";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scalap/2.13.15/scalap-2.13.15.jar";
      sha256 = "sha256-eJkSgtc+nSDL8Ye6uFSc4u+UAmlAnUffKnH6r5r8RhY=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-lang/scalap/2.13.15";
    pkgname = "scalap";
  };
  "scalap-2.13.15-pom" = {
    pname = "scalap-2.13.15-pom";
    version = "2.13.15";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scalap/2.13.15/scalap-2.13.15.pom";
      sha256 = "sha256-3Akl2Ecs39idCEHWKi9TDShnBLJD0m1QyIW3sA0cgLo=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-lang/scalap/2.13.15";
    pkgname = "scalap";
  };
  "shaded-jawn-parser_2.13-1.3.2-bundle" = {
    pname = "shaded-jawn-parser_2.13-1.3.2-bundle";
    version = "1.3.2";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/shaded-jawn-parser_2.13/1.3.2/shaded-jawn-parser_2.13-1.3.2.jar";
      sha256 = "sha256-8yczhMtLlNYAGH5yA3uBXs2qW0RSi7BuyNxHBNSJKIQ=";
    };
    install_path = "https/repo1.maven.org/maven2/com/eed3si9n/shaded-jawn-parser_2.13/1.3.2";
    pkgname = "shaded-jawn-parser_2.13";
  };
  "shaded-jawn-parser_2.13-1.3.2-pom" = {
    pname = "shaded-jawn-parser_2.13-1.3.2-pom";
    version = "1.3.2";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/shaded-jawn-parser_2.13/1.3.2/shaded-jawn-parser_2.13-1.3.2.pom";
      sha256 = "sha256-AzxwUovzVMJDLEU/R5s1/qqJG6HfG51II79cfo5JIBo=";
    };
    install_path = "https/repo1.maven.org/maven2/com/eed3si9n/shaded-jawn-parser_2.13/1.3.2";
    pkgname = "shaded-jawn-parser_2.13";
  };
  "shaded-scalajson_2.13-1.0.0-M4-bundle" = {
    pname = "shaded-scalajson_2.13-1.0.0-M4-bundle";
    version = "1.0.0-M4";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/shaded-scalajson_2.13/1.0.0-M4/shaded-scalajson_2.13-1.0.0-M4.jar";
      sha256 = "sha256-e2tthXJ72KurlAtVnejjKqUIGt0p91MchVuwdhro3mc=";
    };
    install_path = "https/repo1.maven.org/maven2/com/eed3si9n/shaded-scalajson_2.13/1.0.0-M4";
    pkgname = "shaded-scalajson_2.13";
  };
  "shaded-scalajson_2.13-1.0.0-M4-pom" = {
    pname = "shaded-scalajson_2.13-1.0.0-M4-pom";
    version = "1.0.0-M4";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/shaded-scalajson_2.13/1.0.0-M4/shaded-scalajson_2.13-1.0.0-M4.pom";
      sha256 = "sha256-JW0i9tVjTcS+k1jGq2ktgeUR1GjD54NtsoM6PtiKhPg=";
    };
    install_path = "https/repo1.maven.org/maven2/com/eed3si9n/shaded-scalajson_2.13/1.0.0-M4";
    pkgname = "shaded-scalajson_2.13";
  };
  "sjson-new-core_2.13-0.10.1-bundle" = {
    pname = "sjson-new-core_2.13-0.10.1-bundle";
    version = "0.10.1";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/sjson-new-core_2.13/0.10.1/sjson-new-core_2.13-0.10.1.jar";
      sha256 = "sha256-oslg2mcT+Kbp5TUBFuPJ6nM94b1cS+IN/QiZrFqE8F4=";
    };
    install_path = "https/repo1.maven.org/maven2/com/eed3si9n/sjson-new-core_2.13/0.10.1";
    pkgname = "sjson-new-core_2.13";
  };
  "sjson-new-core_2.13-0.10.1-pom" = {
    pname = "sjson-new-core_2.13-0.10.1-pom";
    version = "0.10.1";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/sjson-new-core_2.13/0.10.1/sjson-new-core_2.13-0.10.1.pom";
      sha256 = "sha256-/Yq6w1VOkQ3I7cnEf0kPu3dM6yTBYlMLa2RRcHC1Ips=";
    };
    install_path = "https/repo1.maven.org/maven2/com/eed3si9n/sjson-new-core_2.13/0.10.1";
    pkgname = "sjson-new-core_2.13";
  };
  "sjson-new-core_2.13-0.9.0-bundle" = {
    pname = "sjson-new-core_2.13-0.9.0-bundle";
    version = "0.9.0";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/sjson-new-core_2.13/0.9.0/sjson-new-core_2.13-0.9.0.jar";
      sha256 = "sha256-Z7XJkwjUT6vRRAISDFtey/eWm4V81M5SKeB/34UbLH0=";
    };
    install_path = "https/repo1.maven.org/maven2/com/eed3si9n/sjson-new-core_2.13/0.9.0";
    pkgname = "sjson-new-core_2.13";
  };
  "sjson-new-core_2.13-0.9.0-pom" = {
    pname = "sjson-new-core_2.13-0.9.0-pom";
    version = "0.9.0";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/sjson-new-core_2.13/0.9.0/sjson-new-core_2.13-0.9.0.pom";
      sha256 = "sha256-GF32+3HX2QDpYCd4lq23kLNrpl0pn/KfJwYKs9ZTI+4=";
    };
    install_path = "https/repo1.maven.org/maven2/com/eed3si9n/sjson-new-core_2.13/0.9.0";
    pkgname = "sjson-new-core_2.13";
  };
  "sjson-new-scalajson_2.13-0.10.1-bundle" = {
    pname = "sjson-new-scalajson_2.13-0.10.1-bundle";
    version = "0.10.1";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/sjson-new-scalajson_2.13/0.10.1/sjson-new-scalajson_2.13-0.10.1.jar";
      sha256 = "sha256-zbMyatEPS64nUrHWd3hZ50yqay+HtwppT6I9A0hbjl0=";
    };
    install_path = "https/repo1.maven.org/maven2/com/eed3si9n/sjson-new-scalajson_2.13/0.10.1";
    pkgname = "sjson-new-scalajson_2.13";
  };
  "sjson-new-scalajson_2.13-0.10.1-pom" = {
    pname = "sjson-new-scalajson_2.13-0.10.1-pom";
    version = "0.10.1";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/sjson-new-scalajson_2.13/0.10.1/sjson-new-scalajson_2.13-0.10.1.pom";
      sha256 = "sha256-6u2XGZfMEdLEedMjaeSYZfYQWRTaeZvBj9FpmklttI4=";
    };
    install_path = "https/repo1.maven.org/maven2/com/eed3si9n/sjson-new-scalajson_2.13/0.10.1";
    pkgname = "sjson-new-scalajson_2.13";
  };
  "sourcecode_2.13-0.3.0-bundle" = {
    pname = "sourcecode_2.13-0.3.0-bundle";
    version = "0.3.0";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/sourcecode_2.13/0.3.0/sourcecode_2.13-0.3.0.jar";
      sha256 = "sha256-blstVelCtFCiIr/T68I+mcoDcW5C2iWvGyyM3gOBAPU=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/sourcecode_2.13/0.3.0";
    pkgname = "sourcecode_2.13";
  };
  "sourcecode_2.13-0.3.0-pom" = {
    pname = "sourcecode_2.13-0.3.0-pom";
    version = "0.3.0";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/sourcecode_2.13/0.3.0/sourcecode_2.13-0.3.0.pom";
      sha256 = "sha256-dJd4CGpLVZ8XkdaLTVih6AxgSW8y9TtsH3Xo8hsb/dA=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/sourcecode_2.13/0.3.0";
    pkgname = "sourcecode_2.13";
  };
  "sourcecode_2.13-0.4.0-bundle" = {
    pname = "sourcecode_2.13-0.4.0-bundle";
    version = "0.4.0";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/sourcecode_2.13/0.4.0/sourcecode_2.13-0.4.0.jar";
      sha256 = "sha256-fOm4woWgQoA3TXOde3mUCLLPpAzDFzlghIrsnuhFD+0=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/sourcecode_2.13/0.4.0";
    pkgname = "sourcecode_2.13";
  };
  "sourcecode_2.13-0.4.0-pom" = {
    pname = "sourcecode_2.13-0.4.0-pom";
    version = "0.4.0";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/sourcecode_2.13/0.4.0/sourcecode_2.13-0.4.0.pom";
      sha256 = "sha256-gAhoDXtD/UaX+BQVaxAK+VzLI5uhaEHQpRJXNN/vgs4=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/sourcecode_2.13/0.4.0";
    pkgname = "sourcecode_2.13";
  };
  "spring-framework-bom-5.3.39-pom" = {
    pname = "spring-framework-bom-5.3.39-pom";
    version = "5.3.39";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/springframework/spring-framework-bom/5.3.39/spring-framework-bom-5.3.39.pom";
      sha256 = "sha256-9tSBCT51dny6Gsfh2zj49pLL4+OHRGkzcada6yHGFIs=";
    };
    install_path = "https/repo1.maven.org/maven2/org/springframework/spring-framework-bom/5.3.39";
    pkgname = "spring-framework-bom";
  };
  "test-interface-1.0-bundle" = {
    pname = "test-interface-1.0-bundle";
    version = "1.0";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar";
      sha256 = "sha256-FfcLOLuV8wAv7JrqVAMPGbtOz7rWTGdCS15f6gnNdJ4=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0";
    pkgname = "test-interface";
  };
  "test-interface-1.0-pom" = {
    pname = "test-interface-1.0-pom";
    version = "1.0";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.pom";
      sha256 = "sha256-YboGqdDCJuEPBIAE/Ov7MA/dmwd9Be1QLph1MkyLdi4=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0";
    pkgname = "test-interface";
  };
  "ujson_2.13-3.3.1-bundle" = {
    pname = "ujson_2.13-3.3.1-bundle";
    version = "3.3.1";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/ujson_2.13/3.3.1/ujson_2.13-3.3.1.jar";
      sha256 = "sha256-xh1m171X3hKxELdPDqJxHDRTQ3Y0q1PWj4xEXYZGZgc=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/ujson_2.13/3.3.1";
    pkgname = "ujson_2.13";
  };
  "ujson_2.13-3.3.1-pom" = {
    pname = "ujson_2.13-3.3.1-pom";
    version = "3.3.1";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/ujson_2.13/3.3.1/ujson_2.13-3.3.1.pom";
      sha256 = "sha256-RMlhHCoub+KTqjLl8FVQdn8xWflWq8KYrM7M+lC5Gkk=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/ujson_2.13/3.3.1";
    pkgname = "ujson_2.13";
  };
  "upack_2.13-3.3.1-bundle" = {
    pname = "upack_2.13-3.3.1-bundle";
    version = "3.3.1";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upack_2.13/3.3.1/upack_2.13-3.3.1.jar";
      sha256 = "sha256-h1mYnNUNlpRhBxUsJxTg1b4I9mvsWh4A7FbO2w4gid4=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/upack_2.13/3.3.1";
    pkgname = "upack_2.13";
  };
  "upack_2.13-3.3.1-pom" = {
    pname = "upack_2.13-3.3.1-pom";
    version = "3.3.1";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upack_2.13/3.3.1/upack_2.13-3.3.1.pom";
      sha256 = "sha256-ZDYrD51YSn5WTjH7lnHIAgcfIBhaHG89ii1a2gi/JhA=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/upack_2.13/3.3.1";
    pkgname = "upack_2.13";
  };
  "upickle-core_2.13-3.3.1-bundle" = {
    pname = "upickle-core_2.13-3.3.1-bundle";
    version = "3.3.1";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upickle-core_2.13/3.3.1/upickle-core_2.13-3.3.1.jar";
      sha256 = "sha256-EjUTT9i6j2tan4BK5xBj5J9m3cLiI9cRH2JPvoAKX8Q=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/upickle-core_2.13/3.3.1";
    pkgname = "upickle-core_2.13";
  };
  "upickle-core_2.13-3.3.1-pom" = {
    pname = "upickle-core_2.13-3.3.1-pom";
    version = "3.3.1";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upickle-core_2.13/3.3.1/upickle-core_2.13-3.3.1.pom";
      sha256 = "sha256-WLwd8Rg50yZoKf5B6omNKClP7ZIGEffMXu+cw0nVVKg=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/upickle-core_2.13/3.3.1";
    pkgname = "upickle-core_2.13";
  };
  "upickle-implicits_2.13-3.3.1-bundle" = {
    pname = "upickle-implicits_2.13-3.3.1-bundle";
    version = "3.3.1";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upickle-implicits_2.13/3.3.1/upickle-implicits_2.13-3.3.1.jar";
      sha256 = "sha256-Y11MF6QLCcVRzNuH0YF8hDyrRi/V3AHx+/cBhNYGlWc=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/upickle-implicits_2.13/3.3.1";
    pkgname = "upickle-implicits_2.13";
  };
  "upickle-implicits_2.13-3.3.1-pom" = {
    pname = "upickle-implicits_2.13-3.3.1-pom";
    version = "3.3.1";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upickle-implicits_2.13/3.3.1/upickle-implicits_2.13-3.3.1.pom";
      sha256 = "sha256-rZnqdQ71JfXcHTE+37A3o8Jdip8yanMD+Cwd6UN7i28=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/upickle-implicits_2.13/3.3.1";
    pkgname = "upickle-implicits_2.13";
  };
  "upickle_2.13-3.3.1-bundle" = {
    pname = "upickle_2.13-3.3.1-bundle";
    version = "3.3.1";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upickle_2.13/3.3.1/upickle_2.13-3.3.1.jar";
      sha256 = "sha256-+1fubHgbD1nVrvOshVsrOnr6/dOSJGs0lZ/Hqh6fFb0=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/upickle_2.13/3.3.1";
    pkgname = "upickle_2.13";
  };
  "upickle_2.13-3.3.1-pom" = {
    pname = "upickle_2.13-3.3.1-pom";
    version = "3.3.1";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/com/lihaoyi/upickle_2.13/3.3.1/upickle_2.13-3.3.1.pom";
      sha256 = "sha256-tFGWp9ClpJQfaVBz2kQ7c/IFJzbwrZWHVSKCJUKS9Hc=";
    };
    install_path = "https/repo1.maven.org/maven2/com/lihaoyi/upickle_2.13/3.3.1";
    pkgname = "upickle_2.13";
  };
  "util-control_2.13-1.10.7-bundle" = {
    pname = "util-control_2.13-1.10.7-bundle";
    version = "1.10.7";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-control_2.13/1.10.7/util-control_2.13-1.10.7.jar";
      sha256 = "sha256-3v7edNPa5h8m2W/Nh1LXE/thiZJ8FxWQF66nCRHDxZc=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/util-control_2.13/1.10.7";
    pkgname = "util-control_2.13";
  };
  "util-control_2.13-1.10.7-pom" = {
    pname = "util-control_2.13-1.10.7-pom";
    version = "1.10.7";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-control_2.13/1.10.7/util-control_2.13-1.10.7.pom";
      sha256 = "sha256-8alWX2q/B8a+dum/p/uT8iaUhY0wJW83xre9tiAOvVk=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/util-control_2.13/1.10.7";
    pkgname = "util-control_2.13";
  };
  "util-interface-1.10.3-bundle" = {
    pname = "util-interface-1.10.3-bundle";
    version = "1.10.3";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.10.3/util-interface-1.10.3.jar";
      sha256 = "sha256-r5LTeltP+cZcl3vlBAB7hg2Kf3CPYrjYvkxAzaFSrvY=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/util-interface/1.10.3";
    pkgname = "util-interface";
  };
  "util-interface-1.10.3-pom" = {
    pname = "util-interface-1.10.3-pom";
    version = "1.10.3";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.10.3/util-interface-1.10.3.pom";
      sha256 = "sha256-WTlG7PZuHigdP7le7KpOluR7yGTxBUMeuahXLxIrPuc=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/util-interface/1.10.3";
    pkgname = "util-interface";
  };
  "util-interface-1.10.7-bundle" = {
    pname = "util-interface-1.10.7-bundle";
    version = "1.10.7";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.10.7/util-interface-1.10.7.jar";
      sha256 = "sha256-HWuR76QrcPwGTK7W1iliN04Tsnc3+IWofITGZ7ML5iU=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/util-interface/1.10.7";
    pkgname = "util-interface";
  };
  "util-interface-1.10.7-pom" = {
    pname = "util-interface-1.10.7-pom";
    version = "1.10.7";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.10.7/util-interface-1.10.7.pom";
      sha256 = "sha256-1JRwyBXgcORPlQERbIPzWxeUE/Wq/pXimsKTxnzBYpc=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/util-interface/1.10.7";
    pkgname = "util-interface";
  };
  "util-logging_2.13-1.10.7-bundle" = {
    pname = "util-logging_2.13-1.10.7-bundle";
    version = "1.10.7";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-logging_2.13/1.10.7/util-logging_2.13-1.10.7.jar";
      sha256 = "sha256-+XBNmPixN8tnWLz5nI9NEnMd2al1Z+RomZPJAgxwmQg=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/util-logging_2.13/1.10.7";
    pkgname = "util-logging_2.13";
  };
  "util-logging_2.13-1.10.7-pom" = {
    pname = "util-logging_2.13-1.10.7-pom";
    version = "1.10.7";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-logging_2.13/1.10.7/util-logging_2.13-1.10.7.pom";
      sha256 = "sha256-XfwvDIKtLp8naMPCR0ERqJdfqB8xCuynFcPvs7rCpLg=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/util-logging_2.13/1.10.7";
    pkgname = "util-logging_2.13";
  };
  "util-position_2.13-1.10.7-bundle" = {
    pname = "util-position_2.13-1.10.7-bundle";
    version = "1.10.7";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-position_2.13/1.10.7/util-position_2.13-1.10.7.jar";
      sha256 = "sha256-xk1IrTBqXk3ko7P+NlXXGicCTlrkvY3BpstzancQrmQ=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/util-position_2.13/1.10.7";
    pkgname = "util-position_2.13";
  };
  "util-position_2.13-1.10.7-pom" = {
    pname = "util-position_2.13-1.10.7-pom";
    version = "1.10.7";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-position_2.13/1.10.7/util-position_2.13-1.10.7.pom";
      sha256 = "sha256-NTTRGtvkJ7J87DsFvWKQda+g0eNTdPxNimdWEegeTUQ=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/util-position_2.13/1.10.7";
    pkgname = "util-position_2.13";
  };
  "util-relation_2.13-1.10.7-bundle" = {
    pname = "util-relation_2.13-1.10.7-bundle";
    version = "1.10.7";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-relation_2.13/1.10.7/util-relation_2.13-1.10.7.jar";
      sha256 = "sha256-uyKnk1KDhnVqhP9fvkGi/G/U2bjLDZMTrJ+DHOKnjYI=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/util-relation_2.13/1.10.7";
    pkgname = "util-relation_2.13";
  };
  "util-relation_2.13-1.10.7-pom" = {
    pname = "util-relation_2.13-1.10.7-pom";
    version = "1.10.7";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-relation_2.13/1.10.7/util-relation_2.13-1.10.7.pom";
      sha256 = "sha256-mPAagFGYgS1/BhFCZadQw+o9GI/FGP7ZbnIPKGi480Y=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/util-relation_2.13/1.10.7";
    pkgname = "util-relation_2.13";
  };
  "zero-allocation-hashing-0.16-bundle" = {
    pname = "zero-allocation-hashing-0.16-bundle";
    version = "0.16";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/net/openhft/zero-allocation-hashing/0.16/zero-allocation-hashing-0.16.jar";
      sha256 = "sha256-O8OcZAzIMUV13k68saC8pUBRbTxg1J+N59Y4sJhoVT0=";
    };
    install_path = "https/repo1.maven.org/maven2/net/openhft/zero-allocation-hashing/0.16";
    pkgname = "zero-allocation-hashing";
  };
  "zero-allocation-hashing-0.16-pom" = {
    pname = "zero-allocation-hashing-0.16-pom";
    version = "0.16";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/net/openhft/zero-allocation-hashing/0.16/zero-allocation-hashing-0.16.pom";
      sha256 = "sha256-CUlJaWMZNlX4Gvuduih0NETdKiOm9JM2OKaZHP1yj8Y=";
    };
    install_path = "https/repo1.maven.org/maven2/net/openhft/zero-allocation-hashing/0.16";
    pkgname = "zero-allocation-hashing";
  };
  "zinc-apiinfo_2.13-1.10.7-bundle" = {
    pname = "zinc-apiinfo_2.13-1.10.7-bundle";
    version = "1.10.7";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/zinc-apiinfo_2.13/1.10.7/zinc-apiinfo_2.13-1.10.7.jar";
      sha256 = "sha256-cYm5nHwBBT8ySH2myhiBXmvtrCSvBl6FNLik93vcU6Q=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/zinc-apiinfo_2.13/1.10.7";
    pkgname = "zinc-apiinfo_2.13";
  };
  "zinc-apiinfo_2.13-1.10.7-pom" = {
    pname = "zinc-apiinfo_2.13-1.10.7-pom";
    version = "1.10.7";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/zinc-apiinfo_2.13/1.10.7/zinc-apiinfo_2.13-1.10.7.pom";
      sha256 = "sha256-OwYVqbvStnBjAf2whgujTVSnzsLAutiATwW/JFZkvik=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/zinc-apiinfo_2.13/1.10.7";
    pkgname = "zinc-apiinfo_2.13";
  };
  "zinc-classfile_2.13-1.10.7-bundle" = {
    pname = "zinc-classfile_2.13-1.10.7-bundle";
    version = "1.10.7";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/zinc-classfile_2.13/1.10.7/zinc-classfile_2.13-1.10.7.jar";
      sha256 = "sha256-nnF5MvDjK6lD8FCGc84yCbXiW2WS9XfOnmgE//xU770=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/zinc-classfile_2.13/1.10.7";
    pkgname = "zinc-classfile_2.13";
  };
  "zinc-classfile_2.13-1.10.7-pom" = {
    pname = "zinc-classfile_2.13-1.10.7-pom";
    version = "1.10.7";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/zinc-classfile_2.13/1.10.7/zinc-classfile_2.13-1.10.7.pom";
      sha256 = "sha256-mliyZvw8XRqfc58uYA1TlJem1LPB31hdIqYvKrfG7T8=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/zinc-classfile_2.13/1.10.7";
    pkgname = "zinc-classfile_2.13";
  };
  "zinc-classpath_2.13-1.10.7-bundle" = {
    pname = "zinc-classpath_2.13-1.10.7-bundle";
    version = "1.10.7";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/zinc-classpath_2.13/1.10.7/zinc-classpath_2.13-1.10.7.jar";
      sha256 = "sha256-tuw1MJRZRYNVEZ7zq54KvbkkXs0HK72lpBudV7wymTo=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/zinc-classpath_2.13/1.10.7";
    pkgname = "zinc-classpath_2.13";
  };
  "zinc-classpath_2.13-1.10.7-pom" = {
    pname = "zinc-classpath_2.13-1.10.7-pom";
    version = "1.10.7";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/zinc-classpath_2.13/1.10.7/zinc-classpath_2.13-1.10.7.pom";
      sha256 = "sha256-Jjf1Cq2diwL5r4QntiQZtYFMNtzydELRdLKBKZjEQG8=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/zinc-classpath_2.13/1.10.7";
    pkgname = "zinc-classpath_2.13";
  };
  "zinc-compile-core_2.13-1.10.7-bundle" = {
    pname = "zinc-compile-core_2.13-1.10.7-bundle";
    version = "1.10.7";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/zinc-compile-core_2.13/1.10.7/zinc-compile-core_2.13-1.10.7.jar";
      sha256 = "sha256-knsMrc6+BojLoolkjqk4F145kErA5QH9gzFoecJ5NWA=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/zinc-compile-core_2.13/1.10.7";
    pkgname = "zinc-compile-core_2.13";
  };
  "zinc-compile-core_2.13-1.10.7-pom" = {
    pname = "zinc-compile-core_2.13-1.10.7-pom";
    version = "1.10.7";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/zinc-compile-core_2.13/1.10.7/zinc-compile-core_2.13-1.10.7.pom";
      sha256 = "sha256-HmOO8js1pl4QmkNrel4vhY/KMYxW+zK/ECG9sfqEuaQ=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/zinc-compile-core_2.13/1.10.7";
    pkgname = "zinc-compile-core_2.13";
  };
  "zinc-core_2.13-1.10.7-bundle" = {
    pname = "zinc-core_2.13-1.10.7-bundle";
    version = "1.10.7";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/zinc-core_2.13/1.10.7/zinc-core_2.13-1.10.7.jar";
      sha256 = "sha256-QGuhG+NpI7KZuN/Ubd0pdMqGn3qWJwU1PZ0lFyqYvi8=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/zinc-core_2.13/1.10.7";
    pkgname = "zinc-core_2.13";
  };
  "zinc-core_2.13-1.10.7-pom" = {
    pname = "zinc-core_2.13-1.10.7-pom";
    version = "1.10.7";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/zinc-core_2.13/1.10.7/zinc-core_2.13-1.10.7.pom";
      sha256 = "sha256-eSD1e3nMpEh2qGmqpDf8teUQonOxSD5tuxjOV/TyABo=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/zinc-core_2.13/1.10.7";
    pkgname = "zinc-core_2.13";
  };
  "zinc-persist-core-assembly-1.10.7-bundle" = {
    pname = "zinc-persist-core-assembly-1.10.7-bundle";
    version = "1.10.7";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/zinc-persist-core-assembly/1.10.7/zinc-persist-core-assembly-1.10.7.jar";
      sha256 = "sha256-OM2IJ1HDdTGzgVkITJHwf3Nn4zaNww2tINClfDT/GkI=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/zinc-persist-core-assembly/1.10.7";
    pkgname = "zinc-persist-core-assembly";
  };
  "zinc-persist-core-assembly-1.10.7-pom" = {
    pname = "zinc-persist-core-assembly-1.10.7-pom";
    version = "1.10.7";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/zinc-persist-core-assembly/1.10.7/zinc-persist-core-assembly-1.10.7.pom";
      sha256 = "sha256-UsTMtkr864ZWkrHPUPF7+InVx2xAOrsWxpEYgKaetII=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/zinc-persist-core-assembly/1.10.7";
    pkgname = "zinc-persist-core-assembly";
  };
  "zinc-persist_2.13-1.10.7-bundle" = {
    pname = "zinc-persist_2.13-1.10.7-bundle";
    version = "1.10.7";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/zinc-persist_2.13/1.10.7/zinc-persist_2.13-1.10.7.jar";
      sha256 = "sha256-poVKQotAPDBwhy+mTtjDRpM+GvbB/Ckjl15x0nw+DzE=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/zinc-persist_2.13/1.10.7";
    pkgname = "zinc-persist_2.13";
  };
  "zinc-persist_2.13-1.10.7-pom" = {
    pname = "zinc-persist_2.13-1.10.7-pom";
    version = "1.10.7";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/zinc-persist_2.13/1.10.7/zinc-persist_2.13-1.10.7.pom";
      sha256 = "sha256-T0/ndiueXkaGTnLvOESrH0f7pw1MMdUBMNyFY3MYEKs=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/zinc-persist_2.13/1.10.7";
    pkgname = "zinc-persist_2.13";
  };
  "zinc_2.13-1.10.7-bundle" = {
    pname = "zinc_2.13-1.10.7-bundle";
    version = "1.10.7";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/zinc_2.13/1.10.7/zinc_2.13-1.10.7.jar";
      sha256 = "sha256-w0N8N7Duj+9bHeY0wnZdDoyShHULktA+ixmKCVtebYQ=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/zinc_2.13/1.10.7";
    pkgname = "zinc_2.13";
  };
  "zinc_2.13-1.10.7-pom" = {
    pname = "zinc_2.13-1.10.7-pom";
    version = "1.10.7";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/zinc_2.13/1.10.7/zinc_2.13-1.10.7.pom";
      sha256 = "sha256-uaEzM2xTCAoG5xzluB+YYfawLK7WchV4GBhZq2Nv0LI=";
    };
    install_path = "https/repo1.maven.org/maven2/org/scala-sbt/zinc_2.13/1.10.7";
    pkgname = "zinc_2.13";
  };
}
