# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  arithmetic = {
    pname = "arithmetic";
    version = "3ee6a01d3a078782463ac337561f4949906d500e";
    src = fetchFromGitHub {
      owner = "sequencer";
      repo = "arithmetic";
      rev = "3ee6a01d3a078782463ac337561f4949906d500e";
      fetchSubmodules = false;
      sha256 = "sha256-TDYJMD5BGuROGHc3lOsEG0aFQDXlVXWB0xZ1pMcS7g0=";
    };
    date = "2025-03-20";
  };
  chisel = {
    pname = "chisel";
    version = "d6da96565a7bb25c83a15a1948864c2b8638dd55";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel";
      rev = "d6da96565a7bb25c83a15a1948864c2b8638dd55";
      fetchSubmodules = false;
      sha256 = "sha256-3NyYy77HjLD13AULm09Ikjf0w5Hj/Z2FobaB65SR2eY=";
    };
    date = "2025-05-24";
  };
  chisel-interface = {
    pname = "chisel-interface";
    version = "a61c4d8dbbe25da7c267d03e2be0e24638258023";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel-interface";
      rev = "a61c4d8dbbe25da7c267d03e2be0e24638258023";
      fetchSubmodules = false;
      sha256 = "sha256-cQ0ybo4sxt5X3UOH5NT1f8SmXV+4zeaTo/0zUIr/Kzg=";
    };
    date = "2025-03-20";
  };
  riscv-opcodes = {
    pname = "riscv-opcodes";
    version = "d0c4b0b4ef4c56fbd0499b010342b8107585233e";
    src = fetchFromGitHub {
      owner = "riscv";
      repo = "riscv-opcodes";
      rev = "d0c4b0b4ef4c56fbd0499b010342b8107585233e";
      fetchSubmodules = false;
      sha256 = "sha256-vJigg7GZDUWHmYTc4dsCon7JBs6IW1yY1GRPLfBqkMc=";
    };
    date = "2025-03-19";
  };
  rvdecoderdb = {
    pname = "rvdecoderdb";
    version = "22bd421d3817828a9ed2d45e61a039c9e4ccbfd2";
    src = fetchFromGitHub {
      owner = "sequencer";
      repo = "rvdecoderdb";
      rev = "22bd421d3817828a9ed2d45e61a039c9e4ccbfd2";
      fetchSubmodules = false;
      sha256 = "sha256-q0y9ugElJU+W3dubJ7ITo7/Q2bKz6Mz6cGKIQX9OBA8=";
    };
    date = "2025-05-14";
  };
  zaozi = {
    pname = "zaozi";
    version = "f9d51e942d06367f1227742c77fd1996237fc3eb";
    src = fetchFromGitHub {
      owner = "sequencer";
      repo = "zaozi";
      rev = "f9d51e942d06367f1227742c77fd1996237fc3eb";
      fetchSubmodules = false;
      sha256 = "sha256-0k38DY5bmpsVUKkRpNPr2KfSWhxF8upwCmNb43pdJS4=";
    };
    date = "2025-05-24";
  };
}
