# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  arithmetic = {
    pname = "arithmetic";
    version = "3ee6a01d3a078782463ac337561f4949906d500e";
    src = fetchFromGitHub {
      owner = "sequencer";
      repo = "arithmetic";
      rev = "3ee6a01d3a078782463ac337561f4949906d500e";
      fetchSubmodules = false;
      sha256 = "sha256-TDYJMD5BGuROGHc3lOsEG0aFQDXlVXWB0xZ1pMcS7g0=";
    };
    date = "2025-03-20";
  };
  chisel = {
    pname = "chisel";
    version = "f8ed2b2fd2ac3e9446c7f68f716470397721dc0c";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel";
      rev = "f8ed2b2fd2ac3e9446c7f68f716470397721dc0c";
      fetchSubmodules = false;
      sha256 = "sha256-3P/oisVVCJpTpg2+iRZ73RJVvKSeH6OJDvSwDDiQgzw=";
    };
    date = "2025-05-22";
  };
  chisel-interface = {
    pname = "chisel-interface";
    version = "a61c4d8dbbe25da7c267d03e2be0e24638258023";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel-interface";
      rev = "a61c4d8dbbe25da7c267d03e2be0e24638258023";
      fetchSubmodules = false;
      sha256 = "sha256-cQ0ybo4sxt5X3UOH5NT1f8SmXV+4zeaTo/0zUIr/Kzg=";
    };
    date = "2025-03-20";
  };
  riscv-opcodes = {
    pname = "riscv-opcodes";
    version = "d0c4b0b4ef4c56fbd0499b010342b8107585233e";
    src = fetchFromGitHub {
      owner = "riscv";
      repo = "riscv-opcodes";
      rev = "d0c4b0b4ef4c56fbd0499b010342b8107585233e";
      fetchSubmodules = false;
      sha256 = "sha256-vJigg7GZDUWHmYTc4dsCon7JBs6IW1yY1GRPLfBqkMc=";
    };
    date = "2025-03-19";
  };
  rvdecoderdb = {
    pname = "rvdecoderdb";
    version = "c7acc990037e6b984ab6defb65fdc82f9151c656";
    src = fetchFromGitHub {
      owner = "sequencer";
      repo = "rvdecoderdb";
      rev = "c7acc990037e6b984ab6defb65fdc82f9151c656";
      fetchSubmodules = false;
      sha256 = "sha256-iGZiYBDaUIej9iYAtHWsINAq2LzETKhiQqJB8buA1v4=";
    };
    date = "2025-03-21";
  };
  zaozi = {
    pname = "zaozi";
    version = "0fcf930a61998d2fe9e07571eafe3c25ac494f8c";
    src = fetchFromGitHub {
      owner = "sequencer";
      repo = "zaozi";
      rev = "0fcf930a61998d2fe9e07571eafe3c25ac494f8c";
      fetchSubmodules = false;
      sha256 = "sha256-+W5SbRPyxYKv2SA6jzkML8j0Yp7KLjFTlJou9tvsGoE=";
    };
    date = "2025-05-22";
  };
}
