name: Trigger Physical Design Workflow
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - labeled
env:
  USER: runner

# Cancel the current workflow when new commit pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  generate-test-plan:
    if: '! github.event.pull_request.draft'
    name: "Generate CI target for RTL elaborate"
    runs-on: [self-hosted, linux, nixos]
    outputs:
      testplan: ${{ steps.get-testplan.outputs.testplan }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - id: "get-testplan"
        run: |
          testFile="./designs/org.chipsalliance.t1.elaborator.t1rocketv.T1RocketTile.toml"
          jsonData=$(nix shell ".#dasel" -c dasel -r toml -f "$testFile" -w json)
          echo "testplan=$(echo "$jsonData" | nix shell ".#jq" -c jq -c -r '{ "config": keys }')" \
            > $GITHUB_OUTPUT

  test-emit:
    name: "Test elaborate"
    needs: [generate-test-plan]
    runs-on: [self-hosted, linux, nixos]
    strategy:
      matrix: ${{ fromJSON(needs.generate-test-plan.outputs.testplan) }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: "Test elaborate"
        run: |
          testAttr="t1rocketv"
          testConfig=${{ matrix.config }}
          echo "Building .#t1.${testConfig}.${testAttr}.rtl"
          nix build ".#t1.${testConfig}.${testAttr}.rtl" -L

  physical-design-report:
    name: "Request physical design report"
    if: ${{ success() && (contains(github.event.pull_request.labels.*.name, 'PD-Lane') || contains(github.event.pull_request.labels.*.name, 'PD-Lane-DBG'))}}
    runs-on: [self-hosted, linux, nixos, BIGRAM]
    needs: [test-emit]
    strategy:
      matrix:
        config:
          - blastoise
          - rookidee
    steps:
      - name: "Request report"
        env:
          # Use env key can help us inspect the data
          GH_TOKEN: ${{ secrets.T1_PR_PAT }}
          JSON_CTX: ${{ toJson(github.event.pull_request.labels.*.name) }}
          T1_BRANCH: ${{ github.head_ref || github.ref_name }}
          T1_CONFIG: ${{ matrix.config }}
          T1_COMMIT: ${{ github.event.pull_request.head.sha }}
          PD_URL: ${{ secrets.T1_INHOUSE_URL }}
        run: |
          # GitHub `toJson` will pretty print JSON and causing multiple line escape issue
          # So we have to redirect it to file here
          printf "$JSON_CTX" > _ctx.json
          pdType=$(jq -r 'map(select(. | test("^PD-Lane.*"))) | .[0]' _ctx.json)
          if [[ -z "$pdType" ]] || [[ "$pdType" == "null" ]]; then
            echo "Unable to filter Physical Design type"
            exit 1
          fi

          nix build --impure --out-link fc-result \
            --override-input t1 "github:chipsalliance/t1/${T1_BRANCH}" \
            "git+https://${GH_TOKEN}@${PD_URL}#prometheus.${T1_CONFIG}.tsn28-run-fc-rm.T1RocketTile"

          _CODE_BLOCK='```'

          echo "* Artifacts path: $(realpath fc-result)" >> "$GITHUB_STEP_SUMMARY"
          tee report.md <<-EOF
          T1RocketTile PD Reports
          =======================
          Generated at $(date)

          Information
          -----------
          * commit: $T1_COMMIT
          * branch: $T1_BRANCH
          * config: $T1_CONFIG

          Timing
          ------
          ${_CODE_BLOCK}text
          $(cat fc-result/timing_*.rpt)
          ${_CODE_BLOCK}

          Area
          ----
          ${_CODE_BLOCK}text
          $(cat fc-result/area.rpt)
          ${_CODE_BLOCK}

          Power
          -----
          ${_CODE_BLOCK}text
          $(cat fc-result/power.rpt)
          ${_CODE_BLOCK}

          Logic Level
          -----------
          ${_CODE_BLOCK}text
          $(cat fc-result/logic_levels.rpt)
          ${_CODE_BLOCK}
          EOF

          echo "* Report Short link URL:" >> $GITHUB_STEP_SUMMARY
          echo "<$(curl -Fc=@report.md -Fe=1M https://shz.al | jq -r .url)?lang=md>" >> $GITHUB_STEP_SUMMARY
