name: Test
on: [push]
jobs:
  test:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: make init
      - run: make patch
      - run: make ci
